### ISSUE TITLE
Сделайте пж для Linux

### ISSUE THREAD

**Issue by Igroman4ik228** [N3M1X10/zapret_build#10]
Сделайте пж для Linux тоже самое. Ноут на линуксе. Винду не тянет особо. А эти блокировки всё больше моих любимых сервисов убивают...

**Comment by N3M1X10** [comment]
> Сделайте пж для Linux тоже самое. Ноут на линуксе. Винду не тянет особо. А эти блокировки всё больше моих любимых сервисов убивают...

Попробуйте поискать варианты в темах:
- https://github.com/bol-van/zapret/issues/
- https://github.com/bol-van/zapret/issues/455

Я не спец в линукс
