### ISSUE TITLE
Не открываются сайты

### ISSUE THREAD

**Issue by LeanLee29** [N3M1X10/zapret_build#11]
После запуска службы дискорд работает отлично, но по какой-то причине ютуб никак не заводится, а если быть точнее пишет, что нет доступа в интернет
редактировал адреса в глобальном файле - эффект тот же
плюсом ко всему рандомно перестают открываться сайты
Элементарно та же википедия по какой-то причине просто отваливается, ссылаясь на то, что не удается установить соединение
Сайт того же Ростелекома совсем отвалился, а потом внезапно ожил, но изображения со страницы не грузятся 
Загрузка Стима тоже весьма рандомная штука, главная страница клиента прогружается долго, а в след за этим может поломаться облачная синхра

UAC отключен, сетевые настройки так же сбрасывал и не могу понять, куда копать

**Comment by Dre2dn0ught** [comment]
Ростелеком, всё работает нормально. GoobyeDPILauncher с подходящими настройками включен, ютуб, википедия работают штатно(насколько это можно сказать).

**Comment by N3M1X10** [comment]
Добавил по больше доменов в `list-general.txt`
Может что-то изменится с сайтами?

**Comment by LeanLee29** [comment]
> Добавил по больше доменов в `list-general.txt` Может что-то изменится с сайтами?

К сожалению всё то же самое...
Грешу на Винду
сейчас начисто всё снесу и попробую ещё раз уже на чистой системе

**Comment by Oakenlix** [comment]
Да, то же самое. Рандомные сайты перестают открываться, пока не остановить службу. Потом могут открываться, даже если запустить ее снова. Москва, МГТС.

А ваще огромное спасибо за инструмент!

**Comment by burnedoutman** [comment]
> Да, то же самое. Рандомные сайты перестают открываться, пока не остановить службу. Потом могут открываться, даже если запустить ее снова. Москва, МГТС.
> 
тоже с таким сталкивался, какая-то фигня с днс. пока что костыльно, стопать службу открывать все сайты которые не открываются и снова запускать.

**Comment by LeanLee29** [comment]
> Да, то же самое. Рандомные сайты перестают открываться, пока не остановить службу. Потом могут открываться, даже если запустить ее снова. Москва, МГТС.
> 
> А ваще огромное спасибо за инструмент!

Вот и у меня МТС, и ровно те же проблемы(

**Comment by Oakenlix** [comment]
Щас автор уже добавил отдельный файл, который только на дискорд влияет. Правда его пока надо держать открытым окном. Но мб добавит отдельную службу для него в автозагрузку

**Comment by burnedoutman** [comment]
> > Да, то же самое. Рандомные сайты перестают открываться, пока не остановить службу. Потом могут открываться, даже если запустить ее снова. Москва, МГТС.
> 
> тоже с таким сталкивался, какая-то фигня с днс. пока что костыльно, стопать службу открывать все сайты которые не открываются и снова запускать.

нашёл ещё вариант, можно временно в браузере отключить DoH/DoT
@Oakenlix

**Comment by burnedoutman** [comment]
> Щас автор уже добавил отдельный файл, который только на дискорд влияет. Правда его пока надо держать открытым окном. Но мб добавит отдельную службу для него в автозагрузку

на https://github.com/Flowseal/zapret-discord-youtube/blob/main/service_goodbye_discord.bat
уже всё придумано
