### ISSUE TITLE
Долго грузит ютуб перед воспроизведением 

### ISSUE THREAD

**Issue by Point9045** [N3M1X10/zapret_build#12]
Скачал для дискорда, но и ютуб грузить стабильнее же должен. Боюсь капаться с настройкой, чтоб он не поломался полностью. в Gdpi помогло поменять fake-gen на другие числа. Тут вообще без понятия что менять. Поможете?

**Comment by Point9045** [comment]
Ютуб вроде и работает, только очень грубо. Но у друзей наоборот, говорят даже стал работать лучше на этом билде, чем с gdpi. Пытаюсь разобраться в чем у меня проблема

**Comment by burnedoutman** [comment]
у меня для ютуба такой список, всё летает

```
googlevideo.com
youtu.be
youtube.com
ytimg.com
ggpht.com
youtubekids.com
yt.be
gvt1.com
youtube-nocookie.com
youtube-ui.l.google.com
youtubeembeddedplayer.googleapis.com
youtube.googleapis.com
youtubei.googleapis.com
yt-video-upload.l.google.com
wide-youtube.l.google.com
yt3.ggpht.com
play.google.com
play.google.ru
```

**Comment by LeanLee29** [comment]
> Дополняю. Работал с Zapret сегодня, получилось пофиксить Youtube и Discord. Через некоторое время по одному провайдеру отвалился Ютуб. Страница, превью - грузятся, плеер не грузит.

одно из самых простых решений по оживлению ютуба, которое я нашел для себя: 

https://chromewebstore.google.com/detail/censor-tracker-—-обход-бл/gaidoampbkcknofoejhnhbhbhhifgdop?hl=ru)

ТОЛЬКО ДЛЯ БРАУЗЕРОВ НА ДВИЖКЕ ХРОМИУМ (FireFox, EDGE, Chrome, Yandex) 
Устанавливаем расширение 
переходим в его параметры 
заходим во вкладку "мой список проксируемых сайтов" и вставляем строчки:
googlevideo.com
youtu.be
youtube.com
ytimg.com
ggpht.com
youtubekids.com
yt.be
gvt1.com
youtube-nocookie.com
youtube-ui.l.google.com
youtubeembeddedplayer.googleapis.com
youtube.googleapis.com
youtubei.googleapis.com
yt-video-upload.l.google.com
wide-youtube.l.google.com
yt3.ggpht.com
play.google.com
play.google.ru

**Comment by Resident007** [comment]
> Скачал для дискорда, но и ютуб грузить стабильнее же должен. Боюсь капаться с настройкой, чтоб он не поломался полностью. в Gdpi помогло поменять fake-gen на другие числа. Тут вообще без понятия что менять. Поможете?

Ну допустим, он поломается полностью. В таком случае не вижу ничего сложного в том, чтобы удалить службу, скачать и распаковать репозиторий заново в то же место. Так что экспериментируйте, не бойтесь
