### ISSUE TITLE
Не работает preset_general

### ISSUE THREAD

**Issue by powerofgreed** [N3M1X10/zapret_build#13]
Выключил все впн и dpi штуки. Всё равно не заходит в войс. 
Продолжаю пользоваться Амнезия + Gdpi

**Comment by powerofgreed** [comment]
поменял пресет на "preset_discord.cmd" заработало

**Comment by N3M1X10** [comment]
> поменял пресет на "preset_discord.cmd" заработало

Если требуется разблокировать только дискорд - для этого пресет и отделён от основного

**Comment by N3M1X10** [comment]
> Пожалуйста, добавь пресеты сразу сюда в свой репозиторий. А то людям может быть не удобно самим дописывать и т.д. 

Добавил `Start winws (только discord).bat`

**Comment by powerofgreed** [comment]
> > Пожалуйста, добавь пресеты сразу сюда в свой репозиторий. А то людям может быть не удобно самим дописывать и т.д.
> 
> Добавил `Start winws (только discord).bat`

Так, короче ж фишка в том, что пресет дискорда работает. а 
```
@echo off

call "%~dp0zapret\zapret-winws\preset_russia_general.cmd"

exit
```
Не работает для дискорда, у меня.

**Comment by N3M1X10** [comment]
> > > Пожалуйста, добавь пресеты сразу сюда в свой репозиторий. А то людям может быть не удобно самим дописывать и т.д.
> > 
> > 
> > Добавил `Start winws (только discord).bat`
> 
> Так, короче ж фишка в том, что пресет дискорда работает. а
> 
> ```
> @echo off
> 
> call "%~dp0zapret\zapret-winws\preset_russia_general.cmd"
> 
> exit
> ```
> 
> Не работает для дискорда, у меня.

Не совсем понял чего вы хотите. Пресет дискорда добавить в службы?

**Comment by powerofgreed** [comment]
Нет, я к тому, что общий пресет не работает на дискорд. В моем случае работает только пресет онли с дискордом.
И пару минут назад перестал работать, пока не знаю как это затречить, но через какое-то время перестал работать и присоединяться в войс каналы.

**Comment by powerofgreed** [comment]
Могу я как-то помочь найти в чем проблема и почему перестал работать с дискордом фикс?
Вариант с Амнезией + Gdpi все еще работает.

**Comment by N3M1X10** [comment]
> Могу я как-то помочь найти в чем проблема и почему перестал работать с дискордом фикс? Вариант с Амнезией + Gdpi все еще работает.

Любая помощь будет ценной, поспособствую чем смогу

**Comment by powerofgreed** [comment]
Ну, сам я не знаю какие и где логи сделать чтобы помочь. Могу только оставить удобный фикс людям, которые зайдут сюда за поиском решения. Способ помогает восстановить скорость несмотря на ВПНы.

1. Запускаете GoodByeDPI, заходите в дискорд. 
2. Запускаете Амнезию, либо свой бесплатный. 
3. Заходите в войс канал\открываете стрим\запускаете стрим. И закрываете отключаете впн\амнезию. 
У вас будет ваша скорость и налаженный коннект с войсом.
Так же в амнезии нужно убрать галочку с "Блокировать нетуннелированный трафик"
GBDPI выключать не нужно.

**Comment by N3M1X10** [comment]
https://github.com/N3M1X10/zapret_build/releases/tag/1.0.1
