### ISSUE TITLE
Не помогает в обходе (Экотелеком)

### ISSUE THREAD

**Issue by witwink** [N3M1X10/zapret_build#14]
Пробовал как стандартный вариант, так и службу. Ни YouTube, ни Discord грузится не стали.
Сбрасывал настройки сети, но это не повлияло на работу никак.
Провайдер Экотелеком

**Comment by N3M1X10** [comment]
#6 если там начнут подбирать, можно на их примере проецировать на себя

**Comment by alexmxxre** [comment]
у моего друга экотелеком, сидели наверное пару дней искали решение
в итоге попробуйте так:
1. ну конечно скачайте последнюю запрета 1.5.1
2. сделайте все по инструкции
3. отрубите впн антивирусы и тп
в итоге, в файле discord bat в последней строчке поменяйте на
--filter-tcp=443 --hostlist="%~dp0list-discord.txt" --dpi-desync=fake --dpi-desync-autottl=2 --dpi-desync-autottl6=2 --dpi-desync-fooling=md5sig --dpi-desync-fake-tls="%BIN%tls_clienthello_www_google_com.bin"

**Comment by N3M1X10** [comment]
> 1. ну конечно скачайте последнюю запрета 1.5.1

Не путайте людей ещё сильнее.
Запрет, о котором вы говорите, точнее его вариант сборки - это: https://github.com/Flowseal/zapret-discord-youtube
Репозиторий "запрета" который лежит в основе всего это: https://github.com/bol-van/zapret-win-bundle
