### ISSUE TITLE
Требуется проверка на права администратора для создания/обновления службы

### ISSUE THREAD

**Issue by Hallkezz** [N3M1X10/zapret_build#15]
**Создать или Обновить службу.bat** не сработает без прав администратора, требуется проверка на их наличие.
 
![image](https://github.com/user-attachments/assets/01a9a0cb-7d93-4514-b11b-3cc592de65f3)

**Comment by N3M1X10** [comment]
> **Создать или Обновить службу.bat** не сработает без прав администратора, требуется проверка на их наличие.

Согласен
