### ISSUE TITLE
Создание отдельной службы для дискорда

### ISSUE THREAD

**Issue by KiyoshiGarden** [N3M1X10/zapret_build#16]
В последней версии можно запустить бат с настройками только для дискорда, но при создании службы ставится другой. В итоге некоторые сайты и сервисы снова не грузятся. Можно ли создать службу для батника, который только для Дискорда?

**Comment by N3M1X10** [comment]
Уже в процессе

**Comment by KiyoshiGarden** [comment]
> Да можно, у меня вот таким образом создаёться отдельно для дискорда отдельно для остального. У меня у товарищей работает.
> 
> ```
> set ARGS=--wf-tcp=443-65535 --wf-udp=443-65535 ^
> --filter-udp=443 --hostlist='%~dp0list-discord.txt' --dpi-desync=fake --dpi-desync-udplen-increment=10 --dpi-desync-repeats=6 --dpi-desync-udplen-pattern=0xDEADBEEF --dpi-desync-fake-quic='%~dp0quic_initial_www_google_com.bin' --new ^
> --filter-udp=50000-65535 --dpi-desync=fake,tamper --dpi-desync-any-protocol --dpi-desync-fake-quic='%~dp0quic_initial_www_google_com.bin' --new ^
> --filter-tcp=443 --hostlist='%~dp0list-discord.txt' --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --dpi-desync-fake-tls='%~dp0tls_clienthello_www_google_com.bin'
> call :srvinst winws-discord
> set ARGS=--wf-tcp=80,443 --wf-udp=443 ^
> --filter-udp=443 --hostlist='%~dp0list-youtube.txt' --dpi-desync=fake --dpi-desync-repeats=11 --dpi-desync-fake-quic='%~dp0quic_initial_www_google_com.bin' --new ^
> --filter-udp=443 --dpi-desync=fake --dpi-desync-repeats=11 --new ^
> --filter-tcp=80 --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --new ^
> --filter-tcp=443 --hostlist='%~dp0list-youtube.txt' --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --dpi-desync-fake-tls='%~dp0tls_clienthello_www_google_com.bin' --new ^
> --dpi-desync=fake,disorder2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig
> call :srvinst winws-youtube
> goto :eof
> 
> :srvinst
> net stop %1
> sc delete %1
> sc create %1 binPath= "\"%~dp0winws.exe\" %ARGS%" DisplayName= "zapret DPI bypass : %1" start= auto
> sc description %1 "zapret DPI bypass software"
> sc start %1
> ```

Подскажи, а куда это вставить?

**Comment by N3M1X10** [comment]
https://github.com/N3M1X10/zapret_build/releases/tag/1.0.1
