### ISSUE TITLE
Не работает YouTube.

### ISSUE THREAD

**Issue by Eptiy** [N3M1X10/zapret_build#17]
Сперва хочу поблагодарить автора билда, т.к. работает очень хорошо.

Скорее всего прикол в том, что блокировки у всех разные. Тот же gdpi у меня не работает с готовыми пресетами, приходится время от времени перебирать.
Суть в том, что Дискорд работает стабильно и с хорошим пингом, также работают другие ресусры, напр. Рутрекер. Ютуб же загружает страницу и все её элементы, но плеер не загружается. Когда поверх запрета включаю AmneziaWG с фильтром на айпишники Ютуба, то работать начинает.

Я не очень понимаю, будет ли такой фидбек полезен, и какую ещё инфу можно предоставить, но готов помочь, чем смогу.

**Comment by LeanLee29** [comment]
> Сперва хочу поблагодарить автора билда, т.к. работает очень хорошо.
> 
> Скорее всего прикол в том, что блокировки у всех разные. Тот же gdpi у меня не работает с готовыми пресетами, приходится время от времени перебирать. Суть в том, что Дискорд работает стабильно и с хорошим пингом, также работают другие ресусры, напр. Рутрекер. Ютуб же загружает страницу и все её элементы, но плеер не загружается. Когда поверх запрета включаю AmneziaWG с фильтром на айпишники Ютуба, то работать начинает.
> 
> Я не очень понимаю, будет ли такой фидбек полезен, и какую ещё инфу можно предоставить, но готов помочь, чем смогу.

одно из самых простых решений по оживлению ютуба, которое я нашел для себя:

[https://chromewebstore.google.com/detail/censor-tracker-—-обход-бл/gaidoampbkcknofoejhnhbhbhhifgdop?hl=ru](https://chromewebstore.google.com/detail/censor-tracker-%E2%80%94-%D0%BE%D0%B1%D1%85%D0%BE%D0%B4-%D0%B1%D0%BB/gaidoampbkcknofoejhnhbhbhhifgdop?hl=ru))

ТОЛЬКО ДЛЯ БРАУЗЕРОВ НА ДВИЖКЕ ХРОМИУМ (EDGE, Chrome, Yandex)
Устанавливаем расширение
переходим в его параметры
заходим во вкладку "мой список проксируемых сайтов" и вставляем строчки:
youtube.com 
youtu.be
googlevideo.com
ytimg.com
youtubei.googleapis.com
googleads.g.doubleclick.net
yt3.ggpht.com
static.doubleclick.net
rr1---sn-gvnuxaxjvh-c35z.googlevideo.com
www.youtube.com
accounts.youtube.com
play.google.com
www.gstatic.com
studio.youtube.com

**Comment by N3M1X10** [comment]
https://github.com/N3M1X10/zapret_build/releases/tag/1.0.1

**Comment by Eptiy** [comment]
Ютуб всё ещё не работает.
При запуске любого файла, кроме preset_*, теперь примерно такая картина
![Снимок экрана 2024-10-10](https://github.com/user-attachments/assets/3cc9f4e0-449c-46d0-b031-bd4a79be29f9)

**Comment by N3M1X10** [comment]
> Ютуб всё ещё не работает. При запуске любого файла, кроме preset_*, теперь примерно такая картина ![Снимок экрана 2024-10-10](https://private-user-images.githubusercontent.com/184378098/375076909-3cc9f4e0-449c-46d0-b031-bd4a79be29f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0OTY3NjQsIm5iZiI6MTcyODQ5NjQ2NCwicGF0aCI6Ii8xODQzNzgwOTgvMzc1MDc2OTA5LTNjYzlmNGUwLTQ0OWMtNDZkMC1iMDMxLWJkNGE3OWJlMjlmOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOVQxNzU0MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YzNkM2U3NmRjNmE4MTY0NDljYjJhYjhmNzIxYzJmYmVjMjU2YzFmM2QwMjEwNjlmMTk2ZjgwZGNmODAxNzUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MMhpwmHI_7P7qBO7AzeQ-P9qTps3WowEjS5FHpxqrSA)
> 
> Сами пресеты работают нормально

Это сюда #18
