### ISSUE TITLE
[1.0.0rc2] Глобальный кавардак батников

### ISSUE THREAD

**Issue by AvenCores** [N3M1X10/zapret_build#18]
create_service_general.cmd и create_service_discord.cmd не работают
![image](https://github.com/user-attachments/assets/3e8ef8d4-a220-4acf-b303-fe31c4b744ad)

**Comment by AvenCores** [comment]
> @AvenCores Репозиторий скопирован в старую папку или старая чистилась перед скачиванием?

Полностью чистая скачанная только что

**Comment by LeanLee29** [comment]
> create_service_general.cmd и create_service_discord.cmd не работают ![image](https://private-user-images.githubusercontent.com/64781822/375071355-3e8ef8d4-a220-4acf-b303-fe31c4b744ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0OTU4MjcsIm5iZiI6MTcyODQ5NTUyNywicGF0aCI6Ii82NDc4MTgyMi8zNzUwNzEzNTUtM2U4ZWY4ZDQtYTIyMC00YWNmLWIzMDMtZmUzMWM0Yjc0NGFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDE3Mzg0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhNGQxM2JmYWVhY2JiOWVjYTk0YmNhMjMyNWE1ZDBlZmMxMjU0MzVkYTQ1ZTYxN2NmYmQ3ZWFiYWFkYWNmZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lJYnkbNMhm-MnDC30OqQjKDiSBX7jRM2tsiasIZLvy0)

аналогичная ситуация

**Comment by N3M1X10** [comment]
перезалил эти батники. попробуйте
> Удалил цветастую фигню

**Comment by LeanLee29** [comment]
> перезалил эти батники. попробуйте
> 
> > Удалил цветастую фигню

Сам батник с сервисом Дискорда работает, но служба не создается, соответственно нет подключения к войсу
remove_all_services и remove_service_discord не работают

**Comment by N3M1X10** [comment]
> > перезалил эти батники. попробуйте
> > > Удалил цветастую фигню
> 
> Сам батник с сервисом Дискорда работает, но служба не создается, соответственно нет подключения к войсу remove_all_services и remove_service_discord не работают ![image](https://private-user-images.githubusercontent.com/127203376/375076256-8449ed54-db7b-4c1c-9c7e-bcd235f687aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0OTY0ODIsIm5iZiI6MTcyODQ5NjE4MiwicGF0aCI6Ii8xMjcyMDMzNzYvMzc1MDc2MjU2LTg0NDllZDU0LWRiN2ItNGMxYy05YzdlLWJjZDIzNWY2ODdhYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOVQxNzQ5NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YzhkYWYwOWUyNDk2ZjRjNjM3MzM3YTYyZTUyNWE4YmUyNGY2MmNmZGI2MmVmOThkYmViMGU5NTBlNjY4NjI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._Ek5hoxEO0ja-b4sUSXSfmakQpUA85i0tfHoPSIxrRY)

Их теперь тоже почистил

**Comment by AvenCores** [comment]
> Попробуйте сейчас

не работает
![image](https://github.com/user-attachments/assets/f0614214-b784-42de-876f-5b3e8def89e9)

**Comment by Resident007** [comment]
Тоже не работает, точно такая же проблема как у комментатора выше. Ждем хотфикс

**Comment by N3M1X10** [comment]
убрал проверку пути

**Comment by Resident007** [comment]
> убрал проверку пути

Увы, стало только хуже, хотя я даже запускаю батники из директории билда
![image](https://github.com/user-attachments/assets/a7051487-0e0a-4b65-bab9-375218e9f5a4)

**Comment by AvenCores** [comment]
> убрал проверку пути

![image](https://github.com/user-attachments/assets/b63a713b-7157-44fd-9aac-3a71e673e777)

**Comment by Resident007** [comment]
Тут как будто бы дело не в проверке пути, а в том, как интерпретатор командной строки парсит текст

**Comment by N3M1X10** [comment]
Убрал теперь вообще всё

**Comment by Resident007** [comment]
Да, дело в этом. Я закомментировал вторую строку, и хотя текст превратился в кракозябры, батник корректно отработал.
![image](https://github.com/user-attachments/assets/5caf8d37-c010-4d89-985e-d64485618da5)

**Comment by N3M1X10** [comment]
@Resident007 О, спасибо!!

**Comment by Resident007** [comment]
> > Тут как будто бы дело не в проверке пути, а в том, как интерпретатор командной строки парсит текст
> 
> Так и есть, весь такой текст нужно оборачивать в двойные кавычки а все двойные кавычки внутри убрать или заменить на одиночные.

Кстати очень здравая мысль, у нас же тут .cmd, а не батник. И вообще, в 65001 работаем

**Comment by N3M1X10** [comment]
убрал chcp

Возможно это ещё было связано с тем в какой кодировке я сохранил cmd

**Comment by N3M1X10** [comment]
Короче да, я тупанул с тем что кодировка изначально уже задана. А тут chcp ломает всё

**Comment by LeanLee29** [comment]
> убрал chcp
> 
> Возможно это ещё было связано с тем в какой кодировке я сохранил cmd

Вы настоящий волшебник!)

**Comment by AvenCores** [comment]
> убрал chcp
> 
> Возможно это ещё было связано с тем в какой кодировке я сохранил cmd

ГОЙДА
![image](https://github.com/user-attachments/assets/1a7d55df-1fa3-4fd5-ac69-5836ea89004f)

**Comment by Resident007** [comment]
> убрал chcp
> 
> Возможно это ещё было связано с тем в какой кодировке я сохранил cmd

Да, теперь хорошо. Теперь давай то же самое для всех остальных батников, в т.ч на удаление служб. Уж пуллреквест создавать не буду, уверен ты и сам справишься без меня

**Comment by N3M1X10** [comment]
> > убрал chcp
> > Возможно это ещё было связано с тем в какой кодировке я сохранил cmd
> 
> Да, теперь хорошо. Теперь давай то же самое для всех остальных батников, в т.ч на удаление служб. Уж пуллреквест создавать не буду, уверен ты и сам справишься без меня

Именно это и сделал

**Comment by Resident007** [comment]
> > > убрал chcp
> > > Возможно это ещё было связано с тем в какой кодировке я сохранил cmd
> > 
> > 
> > Да, теперь хорошо. Теперь давай то же самое для всех остальных батников, в т.ч на удаление служб. Уж пуллреквест создавать не буду, уверен ты и сам справишься без меня
> 
> Именно это и сделал

Вообще, если нужна какая-либо еще помощь - дай знать, может помогу чем смогу. Спасибо за работу)
