### ISSUE TITLE
не работает войс в дискорде (lovit)

### ISSUE THREAD

**Issue by SANYNOCHKA** [N3M1X10/zapret_build#19]
Может я не туда жму, но текст и картинки грузятся, но при попытке войти в войс - шиш

Вечное подключение RTC. Провайдер - lovit, будь он проклят

**Comment by Oakenlix** [comment]
Да, та же тема. Еще вчера работало. MGTS.

**Comment by Oakenlix** [comment]
Причем при создании службы появляется текст, намекающий на какую-то ошибку
![image](https://github.com/user-attachments/assets/9e47d5d0-5ec5-4509-9b04-07411161bac2)
при этом служба создается, но не помогает с войсом.

**Comment by N3M1X10** [comment]
Попробуйте подобрать параметры через `zapret\blockcheck\blockcheck.cmd`

**Comment by N3M1X10** [comment]
#34 тут нашли возможное решение
Попробуйте, пока закрываю
