### ISSUE TITLE
Работа с maradns+v2ray?

### ISSUE THREAD

**Issue by YuzuMajere** [N3M1X10/zapret_build#2]
Здравствуйте! С вашей сбокрой заработал дискорд + ютуб на компьютере, за это невероятное Вам спасибо! 

Т.к. я далеко не сетевой инженер, пользуюсь готовыми фиксами; 

* Вопрос такой: До сегодняшнего дня я пользоваться GDPI на компьютере в тандеме с `maradns` + `v2ray`, которые я взял из какого-то поста на пикабу, который прожил около 2 часов, и через вот это все я мог пользоваться ютубом через домашний wifi. Ожидаемо, запрет работает по-другому, и ютуб на телефоне вновь перестал работать. 

* Вполне вероятно, что билд maradns+v2ray был настроен под работу с GDPI, и их можно настроить по-новой. Есть ли у Вас мысли на этот счет?

**Comment by ZenMasterSych** [comment]
Здесь ищите/спрашивайте, там скорее всего уже есть решение https://github.com/bol-van/zapret/issues

**Comment by daniil-gerasimov44** [comment]
надо зайти в конфигурацию батника запрета который ты используешь, посмотреть какой порт используется запретом. далее зайти в конфигурацию v2ray и там после слова "port" написать порт который ты посмотрел у запрета
