### ISSUE TITLE
После перестройки батников создание и удаление служб перестало работать

### ISSUE THREAD

**Issue by Resident007** [N3M1X10/zapret_build#21]
![CnP_09102024_205301](https://github.com/user-attachments/assets/ac8363a1-a4d2-4207-a413-3fffc10b80ef)
Консоль начала выкидывать ошибки синтаксиса. Windows 11 Enterprise 26100, английская

**Comment by N3M1X10** [comment]
> Где-то забыли поставить \ перед спец-символом и всё сломалось.

Там вообще кавардак, я намудрил кое с чем. Сейчас чищу все батники от этих символов

**Comment by N3M1X10** [comment]
#18
