### ISSUE TITLE
не работает ютуб

### ISSUE THREAD

**Issue by Rusinator** [N3M1X10/zapret_build#24]
все сделал по гайду, работает дискорд збс, войс и тд, но ютуб показывает что типа нет инета
провайдер мтс

**Comment by Rusinator** [comment]
![Снимок экрана 2024-10-09 215934](https://github.com/user-attachments/assets/d9952f16-af92-4514-b726-9cab7c27243e)

**Comment by N3M1X10** [comment]
Тоже работает через раз

**Comment by AvenCores** [comment]
https://github.com/N3M1X10/zapret_build/issues/18

**Comment by N3M1X10** [comment]
#12
