### ISSUE TITLE
Использовать кодировку правильно

### ISSUE THREAD

**Issue by shikulja** [N3M1X10/zapret_build#26]
Принудительно форсировать cp1251 не имеет никакого смысла, кроме поломки определения кодировки.

Консоль нативно поддерживает кодировку OEM-866
для определения на гитхаб может быть понадобится добавить строку
:: -*- coding: cp866 -*-

либо через chcp 65001 >nul
в этом случае и гит определяет UTF-8 автоматически
либо chcp 1251 если пользуемся блокнотом)

Такое издевательство, осталось с тех древних времен кто пользовались чистым блокнотом в виндовс и не знали что он открывает все файлы в cp1251, и приходилось форсировать кодировку. 
Не понимаю зачем делать все наоборот, в плохую сторону, ведь все же было правильно. И консоль нативно поддерживает определение кодировки, и строка не мешает, и оптимизации по сути никакой не дает.

**Comment by iCCupPlatoon** [comment]
![image](https://github.com/user-attachments/assets/740de72e-7ddf-41e5-8ac8-5b811e82a0a8)
![image](https://github.com/user-attachments/assets/6728e649-70ca-42b7-b2d1-edfdcb2a0b7b)
Можно выбрать кодировку файла сразу

**Comment by N3M1X10** [comment]
Как только найдёте проблему конкретно в сборке - пожалуйста, дайте знать
