### ISSUE TITLE
Проблемы с Ютубом и другими заблокированными ресурсами

### ISSUE THREAD

**Issue by lilanimetalker** [N3M1X10/zapret_build#27]
Дискорд стабильно хорошо работает, что на службе, что через "preset_general.cmd", но вот другие заблокированные ресурсы...
Ютуб через раз работает и намного дольше грузит, нежели раньше на goodbyedpi.
Другие сервисы, по типу инсты, рутрекера - отказываются работать, только саундклауд пашет, X.
Пробовал сегодня и на первой основной версии репозитория, сейчас на 1.0.1. Пробовал и на разных браузерах.
Что делац?

**Comment by Dirold2** [comment]
Попробуй в zapret_build-1.0.1\zapret\zapret-winws поменять верхнии строчки

googlevideo.com
youtu.be
youtube.com
ytimg.com
ggpht.com
youtubekids.com
yt.be
gvt1.com
youtube-nocookie.com
youtube-ui.l.google.com
youtubeembeddedplayer.googleapis.com
youtube.googleapis.com
youtubei.googleapis.com
yt-video-upload.l.google.com
wide-youtube.l.google.com
yt3.ggpht.com
play.google.com
play.google.ru
i.ytimg.com

На

googlevideo.com
youtubei.googleapis.com
i.ytimg.com

У меня сразу начали прогружаться строчки

**Comment by lilanimetalker** [comment]
> Попробуй в zapret_build-1.0.1\zapret\zapret-winws\list-general.txt поменять верхнии строчки
> 
> googlevideo.com youtu.be youtube.com ytimg.com ggpht.com youtubekids.com yt.be gvt1.com youtube-nocookie.com youtube-ui.l.google.com youtubeembeddedplayer.googleapis.com youtube.googleapis.com youtubei.googleapis.com yt-video-upload.l.google.com wide-youtube.l.google.com yt3.ggpht.com play.google.com play.google.ru i.ytimg.com
> 
> На
> 
> googlevideo.com youtubei.googleapis.com i.ytimg.com
> 
> У меня сразу начали прогружаться видосы

Вроде пока нормас фурычит, но обязательно чекну, как беда начнется.
Больше всего хочется попробовать без впн'ов доступ к рутрекеру получить :(

**Comment by Dirold2** [comment]
[Uploading list-general.txt…]()

Попробуй
