### ISSUE TITLE
Можно ли это использовать как службу?

### ISSUE THREAD

**Issue by leonelo32** [N3M1X10/zapret_build#3]
Можно ли это использовать как службу? Просто не очень удобно при каждом запуске windows видеть окно запуска от им. адм. и потом всё время видеть консоль zapret...

**Comment by N3M1X10** [comment]
> Можно ли это использовать как службу?

Ещё нет, но сделаю

**Comment by N3M1X10** [comment]
Сделал. Пробуйте

**Comment by wicivo** [comment]
> Сделал. Пробуйте

Не работает

**Comment by wicivo** [comment]
![image](https://github.com/user-attachments/assets/b26f75ed-a3d7-42b4-9f2c-fd9322d97592)

**Comment by N3M1X10** [comment]
обновил. попробуйте

**Comment by aksueikava** [comment]
![image](https://github.com/user-attachments/assets/b70c05c8-f136-4941-b83e-a2f08da8b861)

**Comment by N3M1X10** [comment]
От имени администратора?

> ![image](https://private-user-images.githubusercontent.com/135703603/374862576-b70c05c8-f136-4941-b83e-a2f08da8b861.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NjA4NTcsIm5iZiI6MTcyODQ2MDU1NywicGF0aCI6Ii8xMzU3MDM2MDMvMzc0ODYyNTc2LWI3MGMwNWM4LWYxMzYtNDk0MS1iODNlLWEyZjA4ZGE4Yjg2MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOVQwNzU1NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZjAxZmExZWUyMjEzYTVkODI3MmNjN2I3ZmRhMTliYmI3M2U2NjIxMjExMDIwOWVhNmE2MjI0MDU2YjM1YTE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.l1zk8rwaYWs4s8Ubhi_v7tHc2Ukz5DfUBrLDrvji5iM)

**Comment by wicivo** [comment]
воркает

**Comment by aksueikava** [comment]
> От имени администратора?
> 
> > ![image](https://private-user-images.githubusercontent.com/135703603/374862576-b70c05c8-f136-4941-b83e-a2f08da8b861.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NjA4NTcsIm5iZiI6MTcyODQ2MDU1NywicGF0aCI6Ii8xMzU3MDM2MDMvMzc0ODYyNTc2LWI3MGMwNWM4LWYxMzYtNDk0MS1iODNlLWEyZjA4ZGE4Yjg2MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOVQwNzU1NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZjAxZmExZWUyMjEzYTVkODI3MmNjN2I3ZmRhMTliYmI3M2U2NjIxMjExMDIwOWVhNmE2MjI0MDU2YjM1YTE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.l1zk8rwaYWs4s8Ubhi_v7tHc2Ukz5DfUBrLDrvji5iM)

![image](https://github.com/user-attachments/assets/378c3125-80e9-4ceb-9230-b1e65f45aeaf)

**Comment by N3M1X10** [comment]
@aksueikava не знаю в чём проблема.
У некоторых всё ок работает, некоторые такую же ошибку получают.
Разбираюсь сижу

**Comment by N3M1X10** [comment]
По поводу 1060 пишут что службы "Смарт-карта" может не хватать. Перезапуск оной - у товарища не помог
