### ISSUE TITLE
не запускаются службы

### ISSUE THREAD

**Issue by ce1est1a1** [N3M1X10/zapret_build#32]
![image](https://github.com/user-attachments/assets/d1f879e5-a2e6-4858-a5e9-cdc42f97cc44)
что делать

**Comment by Resident007** [comment]
> ![image](https://private-user-images.githubusercontent.com/54845944/375391977-d1f879e5-a2e6-4858-a5e9-cdc42f97cc44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1ODEzNTMsIm5iZiI6MTcyODU4MTA1MywicGF0aCI6Ii81NDg0NTk0NC8zNzUzOTE5NzctZDFmODc5ZTUtYTJlNi00ODU4LWE1ZTktY2RjNDJmOTdjYzQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDE3MjQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2MmYwZTQyYzRhZmQzN2MyN2NkMzM4YzM2NDIxNDQwMjA1MWQyOTM5MGU2OWM2ZTVkM2I3YzZkYTg1NTFkOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hWCtsPETGrxBKWePPA2-1SpHNTAz_ybPnwu4G10vdXw) что делать

Скачать архив через Code - Download ZIP, а не через релизы

**Comment by N3M1X10** [comment]
Залил в [релиз](https://github.com/N3M1X10/zapret_build/releases) ещё один .zip
Попробуйте его скачать

**Comment by ce1est1a1** [comment]
> > ![image](https://private-user-images.githubusercontent.com/54845944/375391977-d1f879e5-a2e6-4858-a5e9-cdc42f97cc44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1ODEzNTMsIm5iZiI6MTcyODU4MTA1MywicGF0aCI6Ii81NDg0NTk0NC8zNzUzOTE5NzctZDFmODc5ZTUtYTJlNi00ODU4LWE1ZTktY2RjNDJmOTdjYzQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDE3MjQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2MmYwZTQyYzRhZmQzN2MyN2NkMzM4YzM2NDIxNDQwMjA1MWQyOTM5MGU2OWM2ZTVkM2I3YzZkYTg1NTFkOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hWCtsPETGrxBKWePPA2-1SpHNTAz_ybPnwu4G10vdXw) что делать
> 
> Скачать архив через Code - Download ZIP, а не через релизы

тоже самое

**Comment by ce1est1a1** [comment]
> Залил в [релиз](https://github.com/N3M1X10/zapret_build/releases) ещё один .zip Попробуйте его скачать

помогло, спасибо
