### ISSUE TITLE
не устанавливается служба

### ISSUE THREAD

**Issue by DranikFour** [N3M1X10/zapret_build#33]
![image](https://github.com/user-attachments/assets/999951fa-8851-4f13-adcd-93532a1f9361)
у меня такая проблема, пробовал смарт карт службу перезапускать и все равно не помогает

**Comment by N3M1X10** [comment]
> у меня такая проблема, пробовал смарт карт службу перезапускать и все равно не помогает

На скриншоте видно что служба создалась и даже запустилась
Но помогает ли она вам с обходом?

**Comment by DranikFour** [comment]
> > у меня такая проблема, пробовал смарт карт службу перезапускать и все равно не помогает
> 
> На скриншоте видно что служба создалась и даже запустилась Но помогает ли она вам с обход

при general работает ютуб, но не работает дискорд, а если запускаю батник только для дискорда - то дискорд работает только когда уже вход выполнен, а когда запускаешь дискорд то на проверке обновления встает просто. На данный момент пользуюсб пока так, сначала запускаю goodbyedpi для ютуба, а после батник только для дискорда и таким образом работает ютуб и дискорд даже при запуске дискорда
