### ISSUE TITLE
Не грузит Ютуб (Ростелеком)

### ISSUE THREAD

**Issue by N3M1X10** [N3M1X10/zapret_build#34]
### От некоторых поступают жалобы на **Ростелеком**
Просьба помочь кто есть с телекома. 
Подберите, пожалуйста, параметры чтобы ютуб завести на операторе. 

### Самостоятельный траблшутинг
Кто может сам попробуйте разобраться, подобрать параметры для пресетов через утилиту `"zapret_build\zapret\blockcheck\blockcheck.cmd"`

# Добавлено решение, попробуйте

На хромиум браузерах важные параметры

Поставить в дэфолт

![image](https://github.com/user-attachments/assets/f9f5a2b4-790a-48ae-8747-0047370835c7)

И отключить Kyber

![image](https://github.com/user-attachments/assets/0f2f0c45-795e-425b-bb35-7d87b3ce5b5f)

**Comment by MAX1MDEV** [comment]
Дискорд тоже перестал работать, Ростелеком

**Comment by N3M1X10** [comment]
Кажется мы починили Ростелеком вместе с одним товарищем

**Comment by MAX1MDEV** [comment]
Починил!
Заменой этой строки:
`--filter-tcp=443 --hostlist="%BIN%list-general.txt" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --dpi-desync-fake-tls="%BIN%tls_clienthello_www_google_com.bin" --new ^`
на:
`--filter-tcp=443 --hostlist="%BIN%list-general.txt" --dpi-desync=fake --dpi-desync-autottl=2 --dpi-desync-autottl6=2 --dpi-desync-fooling=md5sig --dpi-desync-fake-tls="%BIN%tls_clienthello_www_google_com.bin" --new ^`

[zapret_build.zip](https://github.com/user-attachments/files/17343168/zapret_build.zip)

Сделал так в каждом файле, по аналогичной схеме, все работает. Билд твой.

P.S. Тоже Ростелеком.

**Comment by MAX1MDEV** [comment]
> Кажется мы починили Ростелеком вместе с одним товарищем

Ну и отлично :D

**Comment by N3M1X10** [comment]
На хромиум браузерах параметр важно в дэфолт
![image](https://github.com/user-attachments/assets/7e3e8ec1-bc71-4bb8-9c23-744ea3921404)
`preset_youtube_rostelecom.cmd` добавил в dev потестируйте как работает.
Сделаю службу

**Comment by MAX1MDEV** [comment]
> На хромиум браузерах параметр важно в дэфолт ![image](https://private-user-images.githubusercontent.com/48549372/375769074-7e3e8ec1-bc71-4bb8-9c23-744ea3921404.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NTM3MzIsIm5iZiI6MTcyODY1MzQzMiwicGF0aCI6Ii80ODU0OTM3Mi8zNzU3NjkwNzQtN2UzZThlYzEtYmM3MS00YmI4LTljMjMtNzQ0ZWEzOTIxNDA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDEzMzAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1Yjc3MmJkNzBjMjBiMDVmMWU0MGU5NWEwZTVjZDIyMmU4NjU0NjQxZDIzYTdkNzEyNDE4ZDVkYjE5MTAwNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wwi1WyJBm45CsatOC3i4lYGSt1VLurkpczd2swb4q9o) `preset_youtube_rostelecom.cmd` добавил в dev потестируйте как работает. Сделаю службу

Kyber тоже

**Comment by N3M1X10** [comment]
> Kyber тоже

У нас с отключенным завелось, на всякий случай

**Comment by MAX1MDEV** [comment]
> > Kyber тоже
> 
> У нас с отключенным завелось, на всякий случай
> 
> ![image](https://private-user-images.githubusercontent.com/48549372/375771867-a15a3569-0204-478e-b97d-8a192a8d859a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NTM4MjEsIm5iZiI6MTcyODY1MzUyMSwicGF0aCI6Ii80ODU0OTM3Mi8zNzU3NzE4NjctYTE1YTM1NjktMDIwNC00NzhlLWI5N2QtOGExOTJhOGQ4NTlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDEzMzIwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyNTEwMTkzMTQ0MzZhMWM3YTdjOWJiODkxYTNiNGZiNmUyNTg4MGZhMzVhZTAyYWY0NjJkY2RiZGEyNWFmZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ErMuF2dT3v8naXTDTlasBra1v_1LLcNd71SgsK76Ltc)

Кстати, без Kyber быстрее грузится, пинг 96

**Comment by lynegrasd** [comment]
> Починил! Заменой этой строки: `--filter-tcp=443 --hostlist="%BIN%list-general.txt" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --dpi-desync-fake-tls="%BIN%tls_clienthello_www_google_com.bin" --new ^` на: `--filter-tcp=443 --hostlist="%BIN%list-general.txt" --dpi-desync=fake --dpi-desync-autottl=2 --dpi-desync-autottl6=2 --dpi-desync-fooling=md5sig --dpi-desync-fake-tls="%BIN%tls_clienthello_www_google_com.bin" --new ^`
> 
> [zapret_build.zip](https://github.com/user-attachments/files/17343168/zapret_build.zip)
> 
> Сделал так в каждом файле, по аналогичной схеме, все работает. Билд твой.
> 
> P.S. Тоже Ростелеком.

Вот это помогло, хоть у меня мгтс, а не ростелеком

**Comment by N3M1X10** [comment]
закинул в мэйн параметры

**Comment by mironov1338** [comment]
[SC] OpenService: ошибка: 1060:

Указанная служба не установлена.
Кто подскажет как исправить?

**Comment by mironov1338** [comment]
![{4A447FF9-EDC7-44AF-AF2E-F2EB6DDCB18F}](https://github.com/user-attachments/assets/b53b7e54-1df2-4abb-8eec-87f7ca584921)
![{70F394AC-42D8-485A-A0A5-17D45E4F811F}](https://github.com/user-attachments/assets/7489018b-ff40-4992-9e2b-dff9d8a4422a)

Залил в Корень диска С

**Comment by N3M1X10** [comment]
@mironov1338 
> [SC] OpenService: ошибка: 1060:
> 
> Указанная служба не установлена. Кто подскажет как исправить?

Здесь нет никакой ошибки, читай README и проверяй работает ли обход

**Comment by Raelyna** [comment]
Ничего не работает. Пробовала даже "починенный билд" - Ютуб не работает. Думаю, это навсегда

**Comment by Eptiy** [comment]
> Ничего не работает. Пробовала даже "починенный билд" - Ютуб не работает. Думаю, это навсегда

QUIC - по умолчанию, Kyber - выключен? Все батники пробовала? Что такое 'подчинённый билд'?

А вообще до ютуба достучаться можно через блокчек.

**Comment by Raelyna** [comment]
Ну, под "починенным билдом" имелся в виду zapret_build, который zip-ом был скинут выше, от MAX1MDEV

**Comment by Raelyna** [comment]
Kyber - выключила, QUIC у меня и так default, cloudflare-ech в список добавила, сейчас проверю

**Comment by Raelyna** [comment]
Блокчек запустила... И как до ютуба "достучаться" в блокчеке?
![image](https://github.com/user-attachments/assets/a59b57ab-e1ba-42c4-88aa-0b3487bb71aa)

**Comment by Eptiy** [comment]
> Блокчек запустила... И как до ютуба "достучаться" в блокчеке?

Гайд указан в readme билда:
https://github.com/bol-van/zapret/blob/master/docs/quick_start_windows.md

**Comment by Raelyna** [comment]
Гайд вроде почитала, но не совсем поняла...
В общем, указала домен в самом blockcheck.cmd для теста
![image](https://github.com/user-attachments/assets/9650f054-c59b-437a-9b7a-ab0bf6869e26)
Что дальше? Какой ip protocol указывать, и как отвечать на дальнейшие вопросы, на которые ответ либо Yes, либо No (Y/N)?
В readme про blockcheck.cmd я не нашла, только про blockcheck.sh

**Comment by Raelyna** [comment]
Просто вдруг я введу не ту версию IP, и blockcheck сделает ошибочные выводы...

**Comment by Eptiy** [comment]
ipv4, т.е. 4 версию.

**Comment by Raelyna** [comment]
Увы, даже блокчек не помог с ютубом. Буду юзать впн, и все

**Comment by Raelyna** [comment]
Уже даже не знаю, что делать с этим обходом. С ним ютуб уже никогда больше не будет работать. Лучше уж ВПН использовать. Ибо с этим обходом не работает ютуб, а с тем, что от Flowseal, ни аватарки, ни видео не грузятся в дискорде

**Comment by N3M1X10** [comment]
> Уже даже не знаю, что делать с этим обходом. С ним ютуб уже никогда больше не будет работать. Лучше уж ВПН использовать. Ибо с этим обходом не работает ютуб, а с тем, что от Flowseal, ни аватарки, ни видео не грузятся в дискорде

Попробуйте оригинальный чистый zapret winws.
https://github.com/bol-van/zapret-win-bundle

**Comment by Raelyna** [comment]
Теперь больше не работает и дискорд. Как и с запретом от Flowseal. Все заблокировано, можно отказываться от дискорда навсегда

**Comment by Eptiy** [comment]
> Теперь больше не работает и дискорд. Как и с запретом от Flowseal. Что ж, повод отказаться от дискорда навсегда и перейти в ТимСпик

Уже выяснили, что у FLowseal работают general alt2 и alt3.
