### ISSUE TITLE
Не грузится ютуб (мгтс)

### ISSUE THREAD

**Issue by lynegrasd** [N3M1X10/zapret_build#35]
Пробовал со службой и с просто cmd файлом, дискорд работает, но когда захожу на ютуб: 
![Снимок экрана 2024-10-11 142540](https://github.com/user-attachments/assets/35b2ae4a-dfb7-4388-b731-01e0d81bac1c)

провайдер мгтс

**Comment by N3M1X10** [comment]
@lynegrasd  #6
