### ISSUE TITLE
Warzone

### ISSUE THREAD

**Issue by bragin0** [N3M1X10/zapret_build#38]
при запущенном скрипте вылетает варзон стимовский

**Comment by vatruska** [comment]
> при запущенном скрипте вылетает варзон стимовский

А сам стим у тебя нормально работает? А то у меня в клиенте мейн страница магазина вся в ссылках без картинок как будто интерфейс помер, как только выключаю скрипт все нормально становится.

**Comment by N3M1X10** [comment]
> [!NOTE]
> Если не получается найти ответ или получить помощь в данном репозитории - можете 
>
> обратиться в [Репозиторий Flowseal](https://github.com/Flowseal/zapret-discord-youtube)

**Comment by N3M1X10** [comment]
Одна из найденных крайних мер: https://github.com/ValdikSS/GoodbyeDPI/issues/148#issuecomment-2276085368
