### ISSUE TITLE
Bat писались для Linux?

### ISSUE THREAD

**Issue by AceKuper** [N3M1X10/zapret_build#4]
Это моя лучшая догадка, ибо в Windows батники удаления и добавления в автозагрузку не работаю.

В текстовам формате же виден мусор в виде echo [92m�������� �� ��⮧���㧪� �����襭�[96m
Что собственно и не даёт им запускаться нормально.

**Comment by N3M1X10** [comment]
> Это моя лучшая догадка, ибо в Windows батники удаления и добавления в автозагрузку не работаю.

Нет, всё с винды.
автозагрузку сделаю чуть позже через службы

> В текстовам формате же виден мусор в виде echo �[92m�������� �� ��⮧���㧪� �����襭��[96m Что собственно и не даёт им запускаться нормально.

Это текст из другой кодировки. не обязателен для работы, лишь косметика

**Comment by N3M1X10** [comment]
Снёс старый вариант. Закинул автозапуск через службы

**Comment by AceKuper** [comment]
По идее косметика, но вот именно с этим текстом оба батника работать не хотели. Второй особенно интересно выдавал ошибку типа "elet is not a recognized command". Непонятно почему съедая "d" из "delet", может что-то ещё былло проблемой, но именно удаление этого текста позволяло им работать нормально.

**Comment by N3M1X10** [comment]
> По идее косметика, но вот именно с этим текстом оба батника работать не хотели. Второй особенно интересно выдавал ошибку типа "elet is not a recognized command". Непонятно почему съедая "d" из "delet", может что-то ещё былло проблемой, но именно удаление этого текста позволяло им работать нормально.

Там вообще абракадарба из-за этого + кодировка была не в порядке
