### ISSUE TITLE
winws влияет на фоновый процесс запуска игр

### ISSUE THREAD

**Issue by Kristolita** [N3M1X10/zapret_build#41]
Добрый день.
При запущенном батнике только на дискорд (правки настроек на мгтс), происходит следующее.
При запуске некоторых игр из Steam начинается подвисание процесса, видимо рабочего стола. Выглядит это так:
Открыт например Дискорд, браузер, стим. После запуска игры (в моем случае был Hades), происходит видимо частичное зависание рабочего стола. ТК сама игра работает, есть звук, можно даже в меню делать движения, но после alt+tab можно перейти только в окна дискорда и браузера (и диспетчера задач). Сама панель пуска становится неактивной, не запустить программу, не открыть проводник или сам пуск, или настройки. 
Собственно говоря, если грохнуть процесс winws.exe в диспетчере задач, практически сразу всё отвисает и начинает работать.
Вроде не критично, но перезапускать скрипт приходится раз на раз.

**Comment by N3M1X10** [comment]
Пока самый простой костыль - запускать игры без обхода и запускать нужный пресет после успешного входа в игру.

**Comment by N3M1X10** [comment]
https://github.com/ValdikSS/GoodbyeDPI/issues/148#issuecomment-2276085368
