### ISSUE TITLE
Не грузит дискорд все равно

### ISSUE THREAD

**Issue by nojqva** [N3M1X10/zapret_build#42]
Сначала ставил автозапуск, потом просто запускал другие батники. Перед запуском другого батника закрывал дискорд полностью. Просто постоянно висит плашка обновления.
Windows 10 Pro 22H2 19045.4780

**Comment by N3M1X10** [comment]
> Сначала ставил автозапуск, потом просто запускал другие батники. Перед запуском другого батника закрывал дискорд полностью. Просто постоянно висит плашка обновления. Windows 10 Pro 22H2 19045.4780

Убедились в том что служба запущена? 
Нажмите `WIN+R` и в окне введите `services.msc`

**Comment by nojqva** [comment]
Вы там выполняется :)

**Comment by N3M1X10** [comment]
Скорее надо другие параметры подобрать через blockcheck с выключенными обходами

**Comment by nojqva** [comment]
а это я уже хз как

**Comment by Eptiy** [comment]
> а это я уже хз как

[Здесь](https://github.com/Flowseal/zapret-discord-youtube/issues) есть другой вариант обхода блока дс, может он сработает. Плюс, там есть шанс найти уже готовое решение проблемы.

А вот [тут](https://github.com/bol-van/zapret/blob/master/docs/quick_start_windows.txt) описано, как можно самому подобрать настройки для обхода. Это долго и сложно, но по сути - единственный вариант, если не работают другие способы.

**Comment by nojqva** [comment]
> @nojqva
> 
> > а это я уже хз как
> 
> [Здесь](https://github.com/Flowseal/zapret-discord-youtube/issues) есть другой вариант обхода блока дс, может он сработает. Плюс, там есть шанс найти уже готовое решение проблемы.
> 
> А вот [тут](https://github.com/bol-van/zapret/blob/master/docs/quick_start_windows.txt) описано, как можно самому подобрать настройки для обхода. Это долго и сложно, но по сути - единственный вариант, если не работают другие способы.

я у хауди скачал. там сразу все заработало и есть автозапуск в службы.

**Comment by N3M1X10** [comment]
> я у хауди скачал. там сразу все заработало и есть автозапуск в службы.

Приветствуется ссылочка на возможное решение, тем более вашей проблемы :)

**Comment by Eptiy** [comment]
> Приветствуется ссылочка на возможное решение, тем более вашей проблемы :)

Насколько я понял, вот [это](https://howdyho.net/windows-software/discord-fix-snova-rabotayushij-diskord-vojs-zvonki).

**Comment by nojqva** [comment]
> > я у хауди скачал. там сразу все заработало и есть автозапуск в службы.
> 
> Приветствуется ссылочка на возможное решение, тем более вашей проблемы :)

ссылку не вставил, потому что люди обычно удаляют её :) а так да, решение в ссылке, который @Eptiy прислал.

**Comment by N3M1X10** [comment]
> > > я у хауди скачал. там сразу все заработало и есть автозапуск в службы.
> > 
> > 
> > Приветствуется ссылочка на возможное решение, тем более вашей проблемы :)
> 
> ссылку не вставил, потому что люди обычно удаляют её :) а так да, решение в ссылке, который @Eptiy прислал.

Как вариант можете воспользоваться его стратегиями (Хауди)
Утилита та же, драйвер задействован тот же.
