### ISSUE TITLE
Работает ли обход в Турции

### ISSUE THREAD

**Issue by bikxySt** [N3M1X10/zapret_build#44]
Я живу в Турции и утилита не работает у меня. Это может быть связанно с этим? И еще у меня проблема с созданием bat. Не могли бы вы помочь решить ее?
![image](https://github.com/user-attachments/assets/7200bcb6-ffdd-41c7-9787-8bd90827f733)

**Comment by Eptiy** [comment]
> Я живу в Турции и утилита не работает у меня. Это может быть связанно с этим?

Предполагаю, что да.

> И еще у меня проблема с созданием bat. Не могли бы вы помочь решить ее?

А в чём, собственно, проблема?
![376711868-7200bcb6-ffdd-41c7-9787-8bd90827f733](https://github.com/user-attachments/assets/9ea2c1e4-16f9-491e-9ec7-dbe27610e580)
Там же написано, что служба создана и работает.

**Comment by bikxySt** [comment]
"[SC] OpenService FAILED 1060:" - эта строчка меня смущает
Возможно программа у меня не работает из-за ошибки установки, а не из-за региона

**Comment by Eptiy** [comment]
> Возможно программа у меня не работает из-за ошибки установки

Точно нет. Эта строчка отвечает за попытку обновления службы, если я не ошибаюсь. Так как она не установлена, то и обновлять ей нечего.

**Comment by bikxySt** [comment]
Я вообще не задумывался об его методе работы, но мне кажется, что он работает частично, потому что у меня дс пишет "ошибка обновления", то есть он может получать пакеты. Но я не знаток, что бы что либо утверждать, просто делюсь мыслями.

**Comment by Eptiy** [comment]
Можешь попробовать вручную подобрать способ обхода. Вот [тут](https://github.com/bol-van/zapret/blob/master/docs/quick_start_windows.txt) разраб запрета всё расписал.

**Comment by N3M1X10** [comment]
@bikxySt 
Также внимательно на https://github.com/N3M1X10/zapret_build/blob/main/README.md
Там всё расписано

**Comment by N3M1X10** [comment]
> [!NOTE]
> Если не получается найти ответ или получить помощь в данном репозитории,
> всегда можно обратиться к оригинальной документации утилиты zapret и попробовать разобраться со своей проблемой самостоятельно
> - [zapret/docs/quick_start.txt](https://github.com/bol-van/zapret/blob/master/docs/quick_start.txt)
> - [zapret/docs/readme.txt](https://github.com/bol-van/zapret/blob/master/docs/readme.txt)

**Comment by N3M1X10** [comment]
> > Возможно программа у меня не работает из-за ошибки установки
> 
> Точно нет. Эта строчка отвечает за попытку обновления службы, если я не ошибаюсь. Так как она не установлена, то и обновлять ей нечего. У меня в консоли такой же вывод при запуске службы.

Всё так, батник написан для обновления службы. И если её не было - то он ловит ошибку пытаясь удалить её.
Если служба работает, но не помогает в обходе - нужно попробовать подобрать параметры через blockcheck
По ссылке ниже описано как работать с blockcheck. В сборке утилита уже присутствует
- [zapret/docs/quick_start.txt](https://github.com/bol-van/zapret/blob/master/docs/quick_start.txt)
