### ISSUE TITLE
Не работает.Пишет неправильное название файла.

### ISSUE THREAD

**Issue by Dirkog** [N3M1X10/zapret_build#45]
И так на всех zapret 
![Снимок экрана 2024-10-15 235804](https://github.com/user-attachments/assets/0544b69f-6468-4b45-aed3-e698dadb30f0)

**Comment by N3M1X10** [comment]
Антивирус случаем ничего не скушал?

**Comment by Dirkog** [comment]
Нет

ср, 16 окт. 2024 г., 00:01 N3M1X10 ***@***.***>:

**Comment by Dirkog** [comment]
Он у меня отключен

чт, 17 окт. 2024 г., 16:53 Иван Монаенков ***@***.***>:

**Comment by N3M1X10** [comment]
Батник не может найти нужный файл, для создания службы.
Убедитесь что архив распакован, и распакован в папку на которую у вас есть права.
Более я ни чем не могу вам помочь, попробуйте скачать последний релиз и проверьте сохраняется ли проблема.
