### ISSUE TITLE
Служба выдает ошибку, не запускается

### ISSUE THREAD

**Issue by dzenkys** [N3M1X10/zapret_build#47]
![image](https://github.com/user-attachments/assets/03dda1c6-a87c-4873-8b41-1aae0650e4e4)
Запускаю create_service_general.cmd
ОС Win7
Ранее использовал zapret болвана только для дискорда, дискорд работал, сейчас решил попробовать эту сборку для ютуба, и после попытки запустить данную сборку, болванская перестала работать.

UPD1
GoodbyeDPI тоже перестал запускаться и теперь выдает такую страшную штуку:

![image](https://github.com/user-attachments/assets/d5421b24-a545-498b-a556-665479d555f5)

UPD2
Ребут вылечил старую сборку запрета и гудбайдипиай.
При попытке запустить эту сборку винда выдает вот такое, после чего все службы накрываются медным тазом:

![image](https://github.com/user-attachments/assets/7e7a1293-81da-4e19-8988-b1671ea1da72)

**Comment by cringend** [comment]
У меня такая же ошибка, но служба создалась и пока работает. Хотя сегодня в ночь ростелеком прикрыл мне амнезию вг с мусорными пакетами, которая еще днем работала на ура.

**Comment by dzenkys** [comment]
> У меня такая же ошибка, но служба создалась и пока работает. Хотя сегодня в ночь ростелеком прикрыл мне амнезию вг с мусорными пакетами, которая еще днем работала на ура.

Тоже ростелеком, отвалился гудбай сегодня, но с запретом пока не понимаю в чем проблема, в любом случае, тока-что снова нашамал новые настройки гудбай, пока работает. Надеюсь с запретом так мучится не надо если разберусь что с ним у меня не так.
