### ISSUE TITLE
можно ли обойти блок телеграма?

### ISSUE THREAD

**Issue by tangerinz** [N3M1X10/zapret_build#49]
приветствую, живу на северном кавказе, уже две недели у нас глушат телеграм. возможно ли с помощью этого обхода обойти и этот блок, или он работает только на блоки ркн? какие адреса вписывать в текстовый файл для этого?

**Comment by N3M1X10** [comment]
> приветствую, живу на северном кавказе, уже две недели у нас глушат телеграм. возможно ли с помощью этого обхода обойти и этот блок, или он работает только на блоки ркн? какие адреса вписывать в текстовый файл для этого?

Это наверняка возможно.
Вы уже пробовали найти домены телеграм и подобрать параметры через blockcheck?

> [!NOTE]
> - Здесь можно почиатать о том как подбирать параметры для winws [zapret/docs/quick_start.txt](https://github.com/bol-van/zapret/blob/master/docs/quick_start.txt)
> - Здесь полный гигант-гайд по оригинальной утилите [zapret/docs/readme.txt](https://github.com/bol-van/zapret/blob/master/docs/readme.txt)

**Comment by Eptiy** [comment]
cdn-telegram.org
comments.app
contest.com
fragment.com
graph.org
quiz.directory
t.me
tdesktop.com
telega.one
telegra.ph
telegram-cdn.org
telegram.dog
telegram.me
telegram.org
telegram.space
telesco.pe
tg.dev
tx.me
usercontent.dev

**Comment by JMoriarty76** [comment]
Не помогает... Есть альтернатива? (кроме впн)

**Comment by N3M1X10** [comment]
> Не помогает... Есть альтернатива? (кроме впн)

https://github.com/bol-van/zapret/blob/master/docs/quick_start_windows.md
