### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by Scralll** [N3M1X10/zapret_build#5]
![photo_2024-10-09_09-51-10](https://github.com/user-attachments/assets/8148fc16-bf49-4ea7-90f7-6061afcdd936)

При запуске "Start winws" выдает ошибку:
Не удается найти
"G:\Codes\GitHub\Zapret\zapret_build\zapret\zapret-winws\preset_russia+discord.cmd"
Проверьте, правильно ли указано имя и повторите попытку.

**Comment by N3M1X10** [comment]
> При запуске "Start winws" выдает ошибку: Не удается найти "G:\Codes\GitHub\Zapret\zapret_build\zapret\zapret-winws\preset_russia+discord.cmd" Проверьте, правильно ли указано имя и повторите попытку.

Переделал, попробуйте
