### ISSUE TITLE
Как добавать еще сайты типа твиттера?

### ISSUE THREAD

**Issue by ILyasSRS** [N3M1X10/zapret_build#51]
Хочу добавить еще сайтов чтобы работали они тоже твиттер там инсту 7тв

**Comment by Eptiy** [comment]
Выдержка из readme:
* extended.bat - Стратегия для Youtube Discord с добавлением расширенного списка сайтов для разблокировки

Инсту можно разблокировать только [так](https://gist.github.com/illvart/6795f384a71157181b06b5c4a421e768).

C 7tv пока никак, насколько я знаю, но можно, как с инстой, попробовать добавить айпишники в hosts.

**Comment by N3M1X10** [comment]
https://github.com/bol-van/zapret/blob/master/docs/quick_start_windows.md
