### ISSUE TITLE
Можешь пж сделать на Андроид

### ISSUE THREAD

**Issue by livxbox5** [N3M1X10/zapret_build#52]
Здравствуйте хотел спросить вы сможете сделать приложение обход блокировка на Android & Android TV ?
который есть они не рабочие прошу вас  подумайте 
СПАСИБО

**Comment by N3M1X10** [comment]
> Здравствуйте хотел спросить вы сможете сделать приложение обход блокировка на Android & Android TV ? который есть они не рабочие прошу вас подумайте СПАСИБО

Нашёл вариант:
[Форк ByeDPIAndroid](https://github.com/romanvht/ByeDPIAndroid)

В проге есть автоподбор параметров, что может сильно упросить жизнь обывателю
Все варики из оригинальных репо попробовал - не завелось
А этот форк сразу без танцев с бубном помог

**Comment by livxbox5** [comment]
Он у меня не работает
