### ISSUE TITLE
У меня вопрос по поводу zapret

### ISSUE THREAD

**Issue by Psenkoks** [N3M1X10/zapret_build#53]
![photo_2024-10-21_12-05-58](https://github.com/user-attachments/assets/c6984cef-8ebb-4d67-92bb-d4545958f1a3)

Я закинул virustotal на всякий случай, он показывает мне 17 угроз, связанных трояном  с моим компьютером ничего не случится?

**Comment by Eptiy** [comment]
Это не 17 угроз, а 17 проверок из 64 нашли одну угрозу. Эта угроза - драйвер windivert, на котором обход основан. И он не является вирусом, просто под его видом, или с ним в комплекте, некоторые распространяют вирусы. Этот билд чистый, можно не беспокоиться.

**Comment by N3M1X10** [comment]
В оригинальном гайде упоминается что драйвер windivert конфликтует с антивирусами
> [!TIP]
> - [zapret/docs/quick_start_windows.txt](https://github.com/bol-van/zapret/blob/master/docs/quick_start_windows.txt)
> - [zapret/docs/readme.txt](https://github.com/bol-van/zapret/blob/master/docs/readme.txt)
