### ISSUE TITLE
при открытии service_installer.cmd от имени администратора не находит батники

### ISSUE THREAD

**Issue by dezgasting** [N3M1X10/zapret_build#54]
почему-то запуская service_installer.cmd от имени администратора получаю только "Системе не удаётся найти указанный путь" и требования выбрать, а выбрать не получается т.к. ничего не происходит.
![image](https://github.com/user-attachments/assets/25658057-8660-4c05-8354-7b9e8edc8c3a)

причем не запуская от имени администратора список нормально выводится
![image](https://github.com/user-attachments/assets/362a20c1-52b2-48b6-81ea-7453690708de)
но выбирать не рисковал

**Comment by Eptiy** [comment]
Файлы билда все на месте?

**Comment by dezgasting** [comment]
> Файлы билда все на месте? Права на папку есть?

Файлы-то на месте. Права должны быть, по крайней мере я ничего такого не лапал. Так шо либо я чет забыл сделать, либо чето слетело.

**Comment by Eptiy** [comment]
Попробуй заново скачать билд, создать для него папку в корне диска, в названии только латиница без спец символов, добавить её в исключения всех антивирусов, какие есть, выдать в свойствах папки на вкладке "безопасность" полный доступ на свою учётку, поместить чистый архив билда туда, там распаковать, проверить работу.

**Comment by Eptiy** [comment]
Ещё есть подозрение, что прога может не понимать, что ты написал '2', судя по идущей следом надписи 'неверный выбор, завершение'.

Проверь, работают ли батники сами по себе. Проще всего запустить extended и чекнуть пару заблоченных ресурсов. Если всё работает, то там какие-то приколы в самом коде, я в этом не силён, помочь не смогу, но можно попробовать батник установки службы из старого релиза.

**Comment by dezgasting** [comment]
Короче, ставил другой билд, понял в чём дело походу. Нужно поменять название папки, где zapret лежит, чтобы она не имела специальных символов. Всего-то.
