### ISSUE TITLE
discord - no route

### ISSUE THREAD

**Issue by silk1000** [N3M1X10/zapret_build#56]
служб лишних нет
пк перезапускался
при попытке войти в войс чат вылетает **no route** 
запущен обычный .бат для дискорда
из-за чего может быть проблема? 

![image](https://github.com/user-attachments/assets/475fe2f0-8617-4f10-b212-936df79ccb5b)

**Comment by Eptiy** [comment]
Ёмаё, белый дискорд.

Проверь работу обхода с extended, работает ли хоть что-то. Скорее всего конфиг не подходит.

**Comment by Eptiy** [comment]
Если установлен adguard, проверь работу без него.
