### ISSUE TITLE
проблема с обходом блокировки дискорда

### ISSUE THREAD

**Issue by M1kshyy** [N3M1X10/zapret_build#57]
при запуске service.installer.bat от имени администратора и выбрав там дискорд происходит ошибка.

![image](https://github.com/user-attachments/assets/b61767ec-82cf-4bed-b9c8-2e59dd07db7b)
 что делать?

**Comment by Eptiy** [comment]
Скорее всего антивирус удалил нужный файл. Добавь папку в исключения, распакуй в неё билд по новой.

**Comment by M1kshyy** [comment]
> Скорее всего антивирус удалил нужный файл. Добавь папку в исключения, распакуй в неё билд по новой.

а как, обьясните тупому

**Comment by M1kshyy** [comment]
> Скорее всего антивирус удалил нужный файл. Добавь папку в исключения, распакуй в неё билд по новой.
добавление папки в исключение не помогло

**Comment by Eptiy** [comment]
Для начала: какой антивирус у тебя стоит?
