### ISSUE TITLE
Перестал работать батник DIscord

### ISSUE THREAD

**Issue by Chillstream335** [N3M1X10/zapret_build#58]
Перестал работать обход через батник Discord.bat, но если запускать General.bat работает, у меня и у нескольких знакомых с разными провайдерами такая же проблема.

**Comment by oskig** [comment]
буквально 30 минут назад перестал работать, на мгтс. даже не подключается

**Comment by Vaelpurg** [comment]
Подтверждаю. МГТС Московская область, отвалился только Discord, Ютуб и все остальное продолжает работать.

**Comment by ZaiGBeR** [comment]
Такая же проблема

**Comment by simabolotova** [comment]
как удалить вообще эту программу?
чтобы переустановить

**Comment by ttvfreaks** [comment]
Попробуйте в батнике в строке, где `--filter-tcp=443`, флаг `--dpi-desync=fake,split` заменить на `--dpi-desync=disorder2`
Если не сработает, прогоняйте блокчек

**Comment by ZenMasterSych** [comment]
> как удалить вообще эту программу? чтобы переустановить

в папке с ней есть service_remove, нужно от админа запустить

**Comment by oskig** [comment]
> Попробуйте в батнике в строке, где `--filter-tcp=443`, флаг `--dpi-desync=fake,split` заменить на `--dpi-desync=disorder2` Если не сработает, прогоняйте блокчек

Заработало, благодарю!

**Comment by ttvfreaks** [comment]
> > Попробуйте в батнике в строке, где `--filter-tcp=443`, флаг `--dpi-desync=fake,split` заменить на `--dpi-desync=disorder2` Если не сработает, прогоняйте блокчек
> 
> Заработало подключение к самому дискорду, но и на этом спасибо! К голосовым каналам не подключается увы

Может попробовать в строке `--filter-udp=50000-65535 --dpi-desync=fake` поменять `--dpi-desync=fake` на `split`, `split2`, `disorder`, `disorder2`? Конечно совершенно в этом не шарю, но вдруг что-то из этого сработает? Сам проверить не смогу, потому что с войсами проблем не было

**Comment by oskig** [comment]
> > > Попробуйте в батнике в строке, где `--filter-tcp=443`, флаг `--dpi-desync=fake,split` заменить на `--dpi-desync=disorder2` Если не сработает, прогоняйте блокчек
> > 
> > 
> > Заработало подключение к самому дискорду, но и на этом спасибо! К голосовым каналам не подключается увы
> 
> Может попробовать в строке `--filter-udp=50000-65535 --dpi-desync=fake` поменять `--dpi-desync=fake` на `split`, `split2`, `disorder`, `disorder2`? Конечно совершенно в этом не шарю, но вдруг что-то из этого сработает? Сам проверить не смогу, потому что с войсами проблем не было

пробовал но увы не хочет конектиться.
буквально 20 минут назад еще и youtube отвалился на мгтс, что-то мутят эти черти 😢

**Comment by Eptiy** [comment]
Попробуйте снести и начисто поставить последнюю версию. Сегодня у знакомого отвалился дс вообще, ют работал. Сделал так и на extended заработало. Но, конечно, блокчек - самый надёжный вариант.

**Comment by ILyasSRS** [comment]
Ток что отвалился дс

**Comment by N3M1X10** [comment]
Скидывайте свои варианты обхода у кого что и на каком провайдере какого города получилось, вдруг кому-нибудь да и поможете.
