### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by EngiGaming-tf2** [N3M1X10/zapret_build#59]
Вопрос таков, почему **Kaspersky** замечает вашу сборку и сам **вирус** "**not-a-virus:UDS:RiskTool.Multi.WinDivert.gen**"? Просто я не уверен в **честности вашей программы** >:(

**Comment by Eptiy** [comment]
Учись инфу сам искать https://github.com/N3M1X10/zapret_build/issues/53.

**Comment by EngiGaming-tf2** [comment]
> Учись инфу сам искать #53.

Я искал не на Virustotal, у меня Касперский просто.

**Comment by Eptiy** [comment]
Дело не в virus total и касперском. В треде https://github.com/N3M1X10/zapret_build/issues/53 тоже человек спросил про вирусы. Там разраб ответил https://github.com/N3M1X10/zapret_build/issues/53#issuecomment-2428927091.

А вообще можно банально прогуглить RiskTool и выяснить, что это не вирус как таковой; https://threats.kaspersky.com/ru/class/RiskTool/

**Comment by N3M1X10** [comment]
@Eptiy 
Люди только учатся читать, всё нормально )
