### ISSUE TITLE
МГТС Мегатрэд

### ISSUE THREAD

**Issue by Loerft** [N3M1X10/zapret_build#6]
Возможно дело в провайдере(МТС). Все по инструктор установил.

**Comment by N3M1X10** [comment]
> Возможно дело в провайдере(МТС). Все по инструктор установил.

Если вы пробуете через службу - возможно служба не установлена, наблюдаются проблемы с установкой.
Попробуйте ручной запуск через `Start winws.bat` и проверьте

**Comment by Loerft** [comment]
Start winws.bat куда надо вести?

**Comment by N3M1X10** [comment]
> Start winws.bat куда надо вести?

Запустить файл
![image](https://github.com/user-attachments/assets/8e9e49c2-923b-4749-b59b-2a1ff0ab8690)

**Comment by N3M1X10** [comment]
> Все равно не работает. :(

Запускали от имени администратора?
Если и от имени администратора запускали, то проблема пока не известна

**Comment by Dre2dn0ught** [comment]
Такая же ерунда, он просто службу не рисует походу, по какой-то причине.
Один раз сработало, Запустил службу, ребутнулся и пошло нормально, потом перенёс папку, снёс службу, попробовал подрубить по новой и всё, никакого эффекта.

**Comment by Dre2dn0ught** [comment]
В общем он создаёт службу только с папки на рабочем столе. Проверил пару раз, с любого другого места не хочет. А рабочий стол надо держать в чистоте)

**Comment by N3M1X10** [comment]
> В общем он создаёт службу только с папки на рабочем столе. Проверил пару раз, с любого другого места не хочет. А рабочий стол надо держать в чистоте)

Со службами тут разбираемся
https://github.com/N3M1X10/zapret_build/issues/8

**Comment by burnedoutman** [comment]
@Loerft держи, у меня тоже со стандартными на мтс не заработало. через блокчек подобрал

`set ARGS=--wf-tcp=443-65535 --wf-udp=443-65535 ^
--wf-tcp=80,443,50000-65535 --wf-udp=443,50000-65535 ^
--filter-udp=443 --hostlist=\"%~dp0list-general.txt\" --dpi-desync=fake --dpi-desync-udplen-increment=10 --dpi-desync-repeats=6 --dpi-desync-udplen-pattern=0xDEADBEEF --dpi-desync-fake-quic=\"%~dp0quic_initial_www_google_com.bin\" --new ^
--filter-udp=50000-65535 --dpi-desync=fake,tamper --dpi-desync-any-protocol --dpi-desync-fake-quic=\"%~dp0quic_initial_www_google_com.bin\" --new ^
--filter-tcp=80 --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --new ^
--filter-tcp=443 --hostlist=\"%~dp0list-general.txt\" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-split-pos=1 --dpi-desync-fooling=md5sig --dpi-desync-fake-tls=\"%~dp0tls_clienthello_www_google_com.bin\" --new ^
--dpi-desync=fake,disorder2 --dpi-desync-autottl=2

set SRVCNAME=zapret

net stop "%SRVCNAME%"
sc delete "%SRVCNAME%"
sc create "%SRVCNAME%" binPath= "%~dp0winws.exe %ARGS%" DisplayName= "zapret DPI bypass : winws1" start= auto
sc description "%SRVCNAME%" "zapret DPI bypass software"
sc start "%SRVCNAME%"
`

**Comment by prostopadla** [comment]
> @Loerft держи, у меня тоже со стандартными на мтс не заработало. через блокчек подобрал
> 
> `set ARGS=--wf-tcp=443-65535 --wf-udp=443-65535 ^ --wf-tcp=80,443,50000-65535 --wf-udp=443,50000-65535 ^ --filter-udp=443 --hostlist="%~dp0list-general.txt" --dpi-desync=fake --dpi-desync-udplen-increment=10 --dpi-desync-repeats=6 --dpi-desync-udplen-pattern=0xDEADBEEF --dpi-desync-fake-quic="%~dp0quic_initial_www_google_com.bin" --new ^ --filter-udp=50000-65535 --dpi-desync=fake,tamper --dpi-desync-any-protocol --dpi-desync-fake-quic="%~dp0quic_initial_www_google_com.bin" --new ^ --filter-tcp=80 --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --new ^ --filter-tcp=443 --hostlist="%~dp0list-general.txt" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-split-pos=1 --dpi-desync-fooling=md5sig --dpi-desync-fake-tls="%~dp0tls_clienthello_www_google_com.bin" --new ^ --dpi-desync=fake,disorder2 --dpi-desync-autottl=2
> 
> set SRVCNAME=zapret
> 
> net stop "%SRVCNAME%" sc delete "%SRVCNAME%" sc create "%SRVCNAME%" binPath= "%~dp0winws.exe %ARGS%" DisplayName= "zapret DPI bypass : winws1" start= auto sc description "%SRVCNAME%" "zapret DPI bypass software" sc start "%SRVCNAME%" `

Братишка, и куда это девать? Для простых работяг ничего не понятно

**Comment by burnedoutman** [comment]
в батник запихать

**Comment by N3M1X10** [comment]
> > @Loerft держи, у меня тоже со стандартными на мтс не заработало. через блокчек подобрал
> > `set ARGS=--wf-tcp=443-65535 --wf-udp=443-65535 ^ --wf-tcp=80,443,50000-65535 --wf-udp=443,50000-65535 ^ --filter-udp=443 --hostlist="%~dp0list-general.txt" --dpi-desync=fake --dpi-desync-udplen-increment=10 --dpi-desync-repeats=6 --dpi-desync-udplen-pattern=0xDEADBEEF --dpi-desync-fake-quic="%~dp0quic_initial_www_google_com.bin" --new ^ --filter-udp=50000-65535 --dpi-desync=fake,tamper --dpi-desync-any-protocol --dpi-desync-fake-quic="%~dp0quic_initial_www_google_com.bin" --new ^ --filter-tcp=80 --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --new ^ --filter-tcp=443 --hostlist="%~dp0list-general.txt" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-split-pos=1 --dpi-desync-fooling=md5sig --dpi-desync-fake-tls="%~dp0tls_clienthello_www_google_com.bin" --new ^ --dpi-desync=fake,disorder2 --dpi-desync-autottl=2
> > set SRVCNAME=zapret
> > net stop "%SRVCNAME%" sc delete "%SRVCNAME%" sc create "%SRVCNAME%" binPath= "%~dp0winws.exe %ARGS%" DisplayName= "zapret DPI bypass : winws1" start= auto sc description "%SRVCNAME%" "zapret DPI bypass software" sc start "%SRVCNAME%" `
> 
> Братишка, и куда это девать? Для простых работяг ничего не понятно

В данной сборке:
![image](https://github.com/user-attachments/assets/9cedae90-b6a8-4ee3-bedc-71b0663df136)
![image](https://github.com/user-attachments/assets/376530c0-89d9-4fe0-9d3c-bfe9ce95bf84)
![image](https://github.com/user-attachments/assets/8db83a16-e7a5-47a2-a52c-1edfa6bd3b98)

Советую скопировать и сохранить старый файл, подписать к примеру как `preset_russia_general-default.cmd`

**Comment by prostopadla** [comment]
> > > @Loerft держи, у меня тоже со стандартными на мтс не заработало. через блокчек подобрал
> > > `set ARGS=--wf-tcp=443-65535 --wf-udp=443-65535 ^ --wf-tcp=80,443,50000-65535 --wf-udp=443,50000-65535 ^ --filter-udp=443 --hostlist="%~dp0list-general.txt" --dpi-desync=fake --dpi-desync-udplen-increment=10 --dpi-desync-repeats=6 --dpi-desync-udplen-pattern=0xDEADBEEF --dpi-desync-fake-quic="%~dp0quic_initial_www_google_com.bin" --new ^ --filter-udp=50000-65535 --dpi-desync=fake,tamper --dpi-desync-any-protocol --dpi-desync-fake-quic="%~dp0quic_initial_www_google_com.bin" --new ^ --filter-tcp=80 --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --new ^ --filter-tcp=443 --hostlist="%~dp0list-general.txt" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-split-pos=1 --dpi-desync-fooling=md5sig --dpi-desync-fake-tls="%~dp0tls_clienthello_www_google_com.bin" --new ^ --dpi-desync=fake,disorder2 --dpi-desync-autottl=2 set SRVCNAME=zapret net stop "%SRVCNAME%" sc delete "%SRVCNAME%" sc create "%SRVCNAME%" binPath= "%~dp0winws.exe %ARGS%" DisplayName= "zapret DPI bypass : winws1" start= auto sc description "%SRVCNAME%" "zapret DPI bypass software" sc start "%SRVCNAME%" `
> > 
> > 
> > Братишка, и куда это девать? Для простых работяг ничего не понятно
> 
> В данной сборке: ![image](https://private-user-images.githubusercontent.com/48549372/374983041-9cedae90-b6a8-4ee3-bedc-71b0663df136.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0ODIwNDUsIm5iZiI6MTcyODQ4MTc0NSwicGF0aCI6Ii80ODU0OTM3Mi8zNzQ5ODMwNDEtOWNlZGFlOTAtYjZhOC00ZWUzLWJlZGMtNzFiMDY2M2RmMTM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDEzNDkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2MzM0NTMxNzYyZjE4ZDI2YWEwODNiYmViODU1M2ViNjUyMGJkYmVjYjIzMDE5NGIxMmNkZjY0MTFmY2U4M2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aXbr_-jUAyQRB6vQXQuGC9ipBqMlm9WbTgLX3GE4OnE) ![image](https://private-user-images.githubusercontent.com/48549372/374983108-376530c0-89d9-4fe0-9d3c-bfe9ce95bf84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0ODIwNDUsIm5iZiI6MTcyODQ4MTc0NSwicGF0aCI6Ii80ODU0OTM3Mi8zNzQ5ODMxMDgtMzc2NTMwYzAtODlkOS00ZmUwLTlkM2MtYmZlOWNlOTViZjg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDEzNDkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhMWM1ODYyZGFhY2ZiODQzYzQzMzc4N2VmY2I1NTFlNTJlY2FlZjZkN2FlMjQ1ZjU2MDk2NTgzMWMyZjZmOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wZ2HaqbT8-nhTCe3PZeGlfwsLwUv2NRbsZioxUinSdg) ![image](https://private-user-images.githubusercontent.com/48549372/374983226-8db83a16-e7a5-47a2-a52c-1edfa6bd3b98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0ODIwNDUsIm5iZiI6MTcyODQ4MTc0NSwicGF0aCI6Ii80ODU0OTM3Mi8zNzQ5ODMyMjYtOGRiODNhMTYtZTdhNS00N2EyLWE1MmMtMWVkZmE2YmQzYjk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDEzNDkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1MWZkMDViMTZlMDNiZTVjNTljNzY5ODAzMmEwYTJiYmQ4YmFiOWE0NDU5MzgzMjJmNGE3Mzc4OTU0MWE1ZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Za_ayRPUfbPLVy6UuwzpL1Fn6gxQuWUeer7zHeBtpAw)
> 
> Советую скопировать и сохранить старый файл, подписать к примеру как `preset_russia_general-default.cmd`

все равно войс каналы не заработали, клятый МТС

**Comment by burnedoutman** [comment]
а точно установилось? проверьте в списках служб что запрет запущен. старую службу сначала удалили?

**Comment by N3M1X10** [comment]
> все равно войс каналы не заработали, клятый МТС

Он и не запустится если не удалить службу
Запусти `zapret/zapret-winws/remove_service_general.bat`

**Comment by prostopadla** [comment]
> > все равно войс каналы не заработали, клятый МТС
> 
> Он и не запустится если не удалить службу Запусти `zapret/zapret-winws/remove_service_general.bat`

я, очевидно, что-то не так делаю, сто раз всё переустанавливал, перезапускал, не робит

**Comment by Loerft** [comment]
@burnedoutman Приветствую, спасибо конечно за способ. Смог открыт дискорд, но подключится к войс не смог :( Делал по инструкции

**Comment by burnedoutman** [comment]
> @burnedoutman Приветствую, спасибо конечно за способ. Смог открыт дискорд, но подключится к войс не смог :( Делал по инструкции

видимо тогда тебе придётся воспользоваться blockcheck и подбирать параметры под себя

**Comment by Loerft** [comment]
Подскажешь где взять его

**Comment by prostopadla** [comment]
> > Подскажешь где взять его
> 
> `zapret_build\zapret\blockcheck\blockcheck.cmd`

alias blockcheck='"C:/zapret/zapret_build-main/zapret/blockcheck/zapret/blockcheck.sh"'
alias ip2net='"C:/zapret/zapret_build-main/zapret/blockcheck/zapret/ip2net/ip2net"'
alias ll='ls -la'
alias ls='ls --color=auto'
alias mdig='"C:/zapret/zapret_build-main/zapret/blockcheck/zapret/mdig/mdig"'
alias winws='"C:/zapret/zapret_build-main/zapret/blockcheck/zapret/nfq/winws"'
* checking system
CYGWIN detected
firewall type is windivert
* checking already running zapret processes
* checking prerequisites
* checking DNS
system DNS is working
comparing system resolver to public DNS : 8.8.8.8
pornhub.com : OK
ntc.party : OK
rutracker.org : OK
www.torproject.org : OK
bbc.com : OK
checking resolved IP uniqueness for : pornhub.com ntc.party rutracker.org www.torproject.org bbc.com
censor's DNS can return equal result for multiple blocked domains.
all resolved IPs are unique
-- DNS looks good
-- NOTE this check is Russia targeted. In your country other domains may be blocked.
* checking virtualization
cannot detect

NOTE ! this test should be run with zapret or any other bypass software disabled, without VPN

specify domain(s) to test. multiple domains are space separated.
domain(s) (default: rutracker.org) :

И дальше что с этим делать?

**Comment by burnedoutman** [comment]
> > > Подскажешь где взять его
> > 
> > 
> > `zapret_build\zapret\blockcheck\blockcheck.cmd`
> 
> alias blockcheck='"C:/zapret/zapret_build-main/zapret/blockcheck/zapret/blockcheck.sh"' alias ip2net='"C:/zapret/zapret_build-main/zapret/blockcheck/zapret/ip2net/ip2net"' alias ll='ls -la' alias ls='ls --color=auto' alias mdig='"C:/zapret/zapret_build-main/zapret/blockcheck/zapret/mdig/mdig"' alias winws='"C:/zapret/zapret_build-main/zapret/blockcheck/zapret/nfq/winws"'
> 
>     * checking system
>       CYGWIN detected
>       firewall type is windivert
> 
>     * checking already running zapret processes
> 
>     * checking prerequisites
> 
>     * checking DNS
>       system DNS is working
>       comparing system resolver to public DNS : 8.8.8.8
>       pornhub.com : OK
>       ntc.party : OK
>       rutracker.org : OK
>       [www.torproject.org](http://www.torproject.org) : OK
>       bbc.com : OK
>       checking resolved IP uniqueness for : pornhub.com ntc.party rutracker.org [www.torproject.org](http://www.torproject.org) bbc.com
>       censor's DNS can return equal result for multiple blocked domains.
>       all resolved IPs are unique
>       -- DNS looks good
>       -- NOTE this check is Russia targeted. In your country other domains may be blocked.
> 
>     * checking virtualization
>       cannot detect
> 
> 
> NOTE ! this test should be run with zapret or any other bypass software disabled, without VPN
> 
> specify domain(s) to test. multiple domains are space separated. domain(s) (default: rutracker.org) :
> 
> И дальше что с этим делать?

читать что там написано, переводить если не понятно и дальше нажимать

**Comment by prostopadla** [comment]
> > > > Подскажешь где взять его
> > > 
> > > 
> > > `zapret_build\zapret\blockcheck\blockcheck.cmd`
> > 
> > 
> > alias blockcheck='"C:/zapret/zapret_build-main/zapret/blockcheck/zapret/blockcheck.sh"' alias ip2net='"C:/zapret/zapret_build-main/zapret/blockcheck/zapret/ip2net/ip2net"' alias ll='ls -la' alias ls='ls --color=auto' alias mdig='"C:/zapret/zapret_build-main/zapret/blockcheck/zapret/mdig/mdig"' alias winws='"C:/zapret/zapret_build-main/zapret/blockcheck/zapret/nfq/winws"'
> > ```
> > * checking system
> >   CYGWIN detected
> >   firewall type is windivert
> > 
> > * checking already running zapret processes
> > 
> > * checking prerequisites
> > 
> > * checking DNS
> >   system DNS is working
> >   comparing system resolver to public DNS : 8.8.8.8
> >   pornhub.com : OK
> >   ntc.party : OK
> >   rutracker.org : OK
> >   [www.torproject.org](http://www.torproject.org) : OK
> >   bbc.com : OK
> >   checking resolved IP uniqueness for : pornhub.com ntc.party rutracker.org [www.torproject.org](http://www.torproject.org) bbc.com
> >   censor's DNS can return equal result for multiple blocked domains.
> >   all resolved IPs are unique
> >   -- DNS looks good
> >   -- NOTE this check is Russia targeted. In your country other domains may be blocked.
> > 
> > * checking virtualization
> >   cannot detect
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > NOTE ! this test should be run with zapret or any other bypass software disabled, without VPN
> > specify domain(s) to test. multiple domains are space separated. domain(s) (default: rutracker.org) :
> > И дальше что с этим делать?
> 
> читать что там написано, переводить если не понятно и дальше нажимать

братишка, я обычный работяга, которому удосужилось влипнуть в эту ситуацию из-за мтс, я не совсем понимаю, что ты отвечаешь и что мне конкретно нужно сделать, буду признателен за разжёвывание инфы

**Comment by oskig** [comment]
> > > > Подскажешь где взять его
> > > 
> > > 
> > > `zapret_build\zapret\blockcheck\blockcheck.cmd`
> > 
> > 
> > alias blockcheck='"C:/zapret/zapret_build-main/zapret/blockcheck/zapret/blockcheck.sh"' alias ip2net='"C:/zapret/zapret_build-main/zapret/blockcheck/zapret/ip2net/ip2net"' alias ll='ls -la' alias ls='ls --color=auto' alias mdig='"C:/zapret/zapret_build-main/zapret/blockcheck/zapret/mdig/mdig"' alias winws='"C:/zapret/zapret_build-main/zapret/blockcheck/zapret/nfq/winws"'
> > ```
> > * checking system
> >   CYGWIN detected
> >   firewall type is windivert
> > 
> > * checking already running zapret processes
> > 
> > * checking prerequisites
> > 
> > * checking DNS
> >   system DNS is working
> >   comparing system resolver to public DNS : 8.8.8.8
> >   pornhub.com : OK
> >   ntc.party : OK
> >   rutracker.org : OK
> >   [www.torproject.org](http://www.torproject.org) : OK
> >   bbc.com : OK
> >   checking resolved IP uniqueness for : pornhub.com ntc.party rutracker.org [www.torproject.org](http://www.torproject.org) bbc.com
> >   censor's DNS can return equal result for multiple blocked domains.
> >   all resolved IPs are unique
> >   -- DNS looks good
> >   -- NOTE this check is Russia targeted. In your country other domains may be blocked.
> > 
> > * checking virtualization
> >   cannot detect
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > NOTE ! this test should be run with zapret or any other bypass software disabled, without VPN
> > specify domain(s) to test. multiple domains are space separated. domain(s) (default: rutracker.org) :
> > И дальше что с этим делать?
> 
> читать что там написано, переводить если не понятно и дальше нажимать

Тоже МГТС сделал через blockcheck на discord.com и выдало 

* SUMMARY
ipv4 discord.com curl_test_http : working without bypass
ipv4 discord.com curl_test_https_tls12 : winws --wf-l3=ipv4 --wf-tcp=443 --dpi-desync=split2
ipv4 discord.com curl_test_https_tls13 : winws --wf-l3=ipv4 --wf-tcp=443 --dpi-desync=split2
ipv4 discord.com curl_test_http3 : winws --wf-l3=ipv4 --wf-udp=443 --dpi-desync=fake

но когда меняю в строчках батника парметры то ничего не работает всеравно(именно войс)

**Comment by Resident007** [comment]
Единственное решение, которое приходит на ум - пытаться сниффать трафик и смотреть куда лезет дискорд при подключении к войсу, и уже бить блокчеком именно поэтому адресу, по UDP

**Comment by DistorsionInMyMind** [comment]
> > Подскажешь где взять его
> 
> `zapret_build\zapret\blockcheck\blockcheck.cmd`

Плюсую - та же проблема, что и у ТС (как я понимаю - массовая, на этом провайдере).
Будет какой то альтернативный батник для МТС/МГТС с подобранными параметрами?
**Было бы очень хорошо!**

**Comment by N3M1X10** [comment]
> > > Подскажешь где взять его
> > 
> > 
> > `zapret_build\zapret\blockcheck\blockcheck.cmd`
> 
> Плюсую - та же проблема, что и у ТС (как я понимаю - массовая, на этом провайдере). Будет какой то альтернативный батник для МТС/МГТС с подобранными параметрами? **Было бы очень хорошо!**

Ребят, если сможете подобрать сами, на вашем провайдере, можете кинуть пулл реквест с батником.
У меня нет возможности проверить (или навыков)

**Comment by Oakenlix** [comment]
У меня на МГТС получилось!
Вот полное содержание .cmd файла:
`set BIN=%~dp0zapret\zapret-winws\
start "zapret: discord" /min "%BIN%winws.exe" ^
--wf-tcp=80,443,50000-65535 --wf-udp=443,50000-65535 ^
--filter-udp=443 --hostlist="%BIN%list-general.txt" --dpi-desync=fake --dpi-desync-udplen-increment=10 --dpi-desync-repeats=6 --dpi-desync-udplen-pattern=0xDEADBEEF --dpi-desync-fake-quic="%BIN%quic_initial_www_google_com.bin" --new ^
--filter-udp=50000-65535 --dpi-desync=fake,tamper --dpi-desync-any-protocol --dpi-desync-fake-quic="%BIN%quic_initial_www_google_com.bin" --new ^
--filter-tcp=80 --dpi-desync=split --dpi-desync-ttl=4 --dpi-desync-fooling=md5sig --new ^
--filter-tcp=443 --hostlist="%BIN%list-general.txt" --dpi-desync=fake,split2 --dpi-desync-ttl=2 --dpi-desync-split-pos=1
--dpi-desync=fake,disorder2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig`

**Comment by N3M1X10** [comment]
@Oakenlix и остальные кто на МГТС

закинул батник создания службы для дискорда для мгтс, попробуйте

**Comment by N3M1X10** [comment]
> @Oakenlix и остальные кто на МГТС
> 

закинул батник создания службы для дискорда для мгтс, попробуйте
[Меж-релизные изменения теперь здесь](https://github.com/N3M1X10/zapret_build/tree/dev)

**Comment by Loerft** [comment]
Спасибо вам за помощь. Попробовал запустить все работает! кроме войса :(

**Comment by Loerft** [comment]
Да

**Comment by N3M1X10** [comment]
general плюс mgts попробуйте.
Методом тыка

**Comment by Oakenlix** [comment]
> > @Oakenlix и остальные кто на МГТС
> 
> закинул батник создания службы для дискорда для мгтс, попробуйте [Меж-релизные изменения теперь здесь](https://github.com/N3M1X10/zapret_build/tree/dev)
> 
> ![image](https://private-user-images.githubusercontent.com/48549372/375736266-880a8aa6-4334-4ba7-b17d-eff9292da9fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NDcyMjcsIm5iZiI6MTcyODY0NjkyNywicGF0aCI6Ii80ODU0OTM3Mi8zNzU3MzYyNjYtODgwYThhYTYtNDMzNC00YmE3LWIxN2QtZWZmOTI5MmRhOWZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDExNDIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5ZGE3OTUxYTU2NmIzYjA0ZDUwYmE5Y2Y3ODc2OGRlZTZlNTI0NWFhZmE4ZTA4ODVlN2YzYjFjOGRjZmZhNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qb9G4UAG1SrZWSshbMlZ0_cwFoLdL7O3SX-cZmFhVVg)

У меня запускается, работает. Спасибо! 
PS: речь именно о дискорде если что, с ютубом вроде не помогает, но мне и не надо

**Comment by Oakenlix** [comment]
> Спасибо вам за помощь. Попробовал запустить все работает! кроме войса :(

Напиши мне в дискорде, ник такой же, я вроде понял как находить нужные опции через блокчек

**Comment by Loerft** [comment]
> general плюс discord_mgts попробуйте. Методом тыка

Сейчас попробую все переустановить. Может заработает

**Comment by N3M1X10** [comment]
> как находить нужные опции через блокчек

https://github.com/bol-van/zapret/blob/master/docs/quick_start_windows.txt

**Comment by Loerft** [comment]
Мы сначала запускаем службу МГТС и потом основной?

**Comment by N3M1X10** [comment]
> Мы сначала запускаем службу МГТС и потом основной?

сделай отдельный батник c текстом как [тут](https://github.com/N3M1X10/zapret_build/issues/6#issuecomment-2407048471)

**Comment by Loerft** [comment]
![image](https://github.com/user-attachments/assets/ffc92b56-e28b-49dd-939d-c44297c861ed)
![image](https://github.com/user-attachments/assets/adec127c-f4fc-406e-aafd-dea56e7aad8e)

**Comment by N3M1X10** [comment]
Служба не запустилась, "Состояние: 2"
Запущена - 4

**Comment by Loerft** [comment]
> Служба не запустилась, "Состояние: 2" Запущена - 4

Как понимаю надо измените?

**Comment by Loerft** [comment]
> Служба не запустилась, "Состояние: 2" Запущена - 4

Спасибо вам огромной! Все решилось. Хорошего дня :)

**Comment by lynegrasd** [comment]
а если дискорд заработал, а ютуб нет? (preset_general , preset_discord_mgts не помогает) пишет нет подключения к интернету

**Comment by N3M1X10** [comment]
Посмотрите параметры хрома как тут #34

**Comment by N3M1X10** [comment]
@Oakenlix @Loerft
И попробуйте без mgts службы запуститься и проверить всё

**Comment by Oakenlix** [comment]
> @Oakenlix @Loerft И попробуйте без mgts службы запуститься и проверить всё

Поменял в службе general параметры как здесь https://github.com/N3M1X10/zapret_build/issues/34#issuecomment-2407408382

И теперь работает и ютуб, и дискорд с войсом

**Comment by plutik1** [comment]
товарищи спасайте что нужно сделать чтобы у МТС заработало, все что выше не хочет

**Comment by Oakenlix** [comment]
> товарищи спасайте что нужно сделать чтобы у МТС заработало, все что выше не хочет

Что именно не работает, ютуб или дискорд?

**Comment by plutik1** [comment]
дис

**Comment by Oakenlix** [comment]
> У меня на МГТС получилось! Как сделать со службой пока хз, я и с блокчеком разобрался только чудом каким-то PS: саму связь пока не тестил, но к войсу подключается нормально Вот полное содержание .cmd файла: `set BIN=%~dp0zapret\zapret-winws\ start "zapret: discord" /min "%BIN%winws.exe" ^ --wf-tcp=80,443,50000-65535 --wf-udp=443,50000-65535 ^ --filter-udp=443 --hostlist="%BIN%list-discord.txt" --dpi-desync=fake --dpi-desync-udplen-increment=10 --dpi-desync-repeats=6 --dpi-desync-udplen-pattern=0xDEADBEEF --dpi-desync-fake-quic="%BIN%quic_initial_www_google_com.bin" --new ^ --filter-udp=50000-65535 --dpi-desync=fake,tamper --dpi-desync-any-protocol --dpi-desync-fake-quic="%BIN%quic_initial_www_google_com.bin" --new ^ --filter-tcp=80 --dpi-desync=split --dpi-desync-ttl=4 --dpi-desync-fooling=md5sig --new ^ --filter-tcp=443 --hostlist="%BIN%list-discord.txt" --dpi-desync=fake,split2 --dpi-desync-ttl=2 --dpi-desync-split-pos=1 --dpi-desync=fake,disorder2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig`

@plutik1 вот это тоже не помогло?

**Comment by plutik1** [comment]
в общем как бы странно не звучало, но 4 перезапуска компа и в какой то итерации оно заработало 
--filter-udp=443 --hostlist="list-discord.txt" --dpi-desync=fake --dpi-desync-udplen-increment=10 --dpi-desync-repeats=6 --dpi-desync-udplen-pattern=0xDEADBEEF --dpi-desync-fake-quic="%BIN%quic_initial_www_google_com.bin" --new ^

**Comment by N3M1X10** [comment]
> в общем как бы странно не звучало, но 4 перезапуска компа и в какой то итерации оно заработало

Комп не обязательно перезапускать вроде?

**Comment by plutik1** [comment]
именно после перезагрузки заработало, в этом прикол

**Comment by Oakenlix** [comment]
Бывало когда-то такое, что служба есть, но в приостановленном состоянии. Мб с этим перезагрузка помогает, хз

**Comment by N3M1X10** [comment]
> Бывало когда-то такое, что служба есть, но в приостановленном состоянии. Мб с этим перезагрузка помогает, хз

В этом помогает пожмать батник создания службы, до тех пор пока не выдаст:

![image](https://github.com/user-attachments/assets/36884e58-18cb-4bab-acb5-a12fcd0f4199)

Состояние службы: 4

**Comment by L3rx1** [comment]
При запуске перестает грузиться twitch, чат продолжает бежать, а вот сам стрим не открывается

**Comment by N3M1X10** [comment]
@Oakenlix 
> Бывало когда-то такое, что служба есть, но в приостановленном состоянии. Мб с этим перезагрузка помогает, хз

Windivert не запущен или в стазисе, в этом помогает запустить вручную любой пресет.
Обновил README по поводу в ветке [DEV](https://github.com/N3M1X10/zapret_build/tree/dev)
