### ISSUE TITLE
открывает дискорд, но не работает голосовая связь

### ISSUE THREAD

**Issue by notsouseful572** [N3M1X10/zapret_build#60]
работает всё прекрасно, кроме дискорда, бесконечное RTC connecting, чаты и каналы в порядке

**Comment by Rake1123** [comment]
та же проблема!

**Comment by N3M1X10** [comment]
Если не работает стандартная стратегия, пробуем подобрать под себя через блокчек:
- Гайд по самостоятельному подбору стратегий [zapret/docs/quick_start_windows.txt](https://github.com/bol-van/zapret/blob/master/docs/quick_start_windows.txt)

---

> [!TIP]
> Если не получается найти ответ или получить помощь в данном репозитории,
> всегда можно обратиться к оригинальной документации утилиты zapret и попробовать разобраться со своей проблемой самостоятельно
> - [zapret/docs/quick_start_windows.txt](https://github.com/bol-van/zapret/blob/master/docs/quick_start_windows.txt)
> - [zapret/docs/quick_start.txt](https://github.com/bol-van/zapret/blob/master/docs/quick_start.txt)
> - [zapret/docs/readme.txt](https://github.com/bol-van/zapret/blob/master/docs/readme.txt)
