### ISSUE TITLE
Работает не на всех устройствах

### ISSUE THREAD

**Issue by HxppyCompany** [N3M1X10/zapret_build#61]
Сначала установил по рекомендации друга на свой пк эту утилиту и всё было замечательно. Но я установил на свой ноут эту же версию утилиты и она не заработала. 

В списке служб отображается и говорит, что запущена и работает исправно. Пробовал переустанавливать и перезагружать ноут, но всё тщетно. Так же обновил его до последней версии.

Единственное, что мне показалось странным, это ошибка, которая возникает при первом запуске, которая говорит, что такая служба не найдена. Но я предполагаю это просто попытка завершить службу на тот случай, если я хочу заменить запущенную ранее.

Не исключаю вероятность, что какая-то программа ломает работу этой утилиты. На моём ноутбуке например есть программа Killer Control Center и вместо MSI Center - MSI Center Pro.

### Технические характеристики:
- Модель: MSI Summit E13 Flip Evo
- Процессор: 12th Gen Intel(R) Core(TM) i5-1240P   2.10 GHz
- Тип системы: 64-разрядная операционная система, процессор x64
### ОС:
- Выпуск: Windows 11 Pro
- Версия: 23H2
- Дата установки: ‎12/‎10/‎2022
- Сборка ОС: 22631.4391
- Взаимодействие: Windows Feature Experience Pack 1000.22700.1047.0

![image](https://github.com/user-attachments/assets/35b29e8e-a7fb-40c1-bb30-9b6223bdbbfb)

### Технические характеристики:
- Материнская плата: MSI MAG B560 TOMAHAWK WIFI
- Процессор: 11th Gen Intel(R) Core(TM) i5-11600K @ 3.90GHz   3.91 GHz
- Тип системы: 64-разрядная операционная система, процессор x64
### ОС:
- Выпуск: Windows 11 Pro
- Версия: 23H2
- Дата установки: ‎4/‎19/‎2024
- Сборка ОС: 22631.4391
- Взаимодействие: Windows Feature Experience Pack 1000.22700.1047.0

![image](https://github.com/user-attachments/assets/9a5fe1f3-a498-4c90-846a-39917c23d81d)

С нетерпением жду вашей помощи!

**Comment by Eptiy** [comment]
Говорят, что отключение Killer Network Service помогает.

**Comment by HxppyCompany** [comment]
правда помогло, спасибо!

**Comment by HxppyCompany** [comment]
Но хотелось бы, чтобы было решение без отключения утилиты Killer Control Center. Местами он полезен, как минимум своей функцией Killer Xtend

**Comment by Eptiy** [comment]
Я не уверен, можно ли что-то сделать. Ждём ответ разраба билда @N3M1X10.

Проверь пока, работает ли батник, а не служба, совместно с киллером.

**Comment by HxppyCompany** [comment]
Батник уже тоже пробовал запускать отдельно, не помогло. Тоже не дало никакого эффекта

**Comment by Eptiy** [comment]
https://github.com/Flowseal/zapret-discord-youtube/discussions/252#discussioncomment-11128476
Можешь тут ещё у людей поспрашивать.

**Comment by N3M1X10** [comment]
> Но хотелось бы, чтобы было решение без отключения утилиты Killer Control Center. Местами он полезен, как минимум своей функцией Killer Xtend

Погуглил галопом - не нашёл простых способов. Если требуется - прошу вас, ищите решение сами.
Вероятно для этого потребуется построить целый замок из костылей, так как и то и другое работает с трафиком и пытается его контролировать.
