### ISSUE TITLE
Не создаётся служба

### ISSUE THREAD

**Issue by N3M1X10** [N3M1X10/zapret_build#8]
![image](https://private-user-images.githubusercontent.com/135703603/374862941-378c3125-80e9-4ceb-9230-b1e65f45aeaf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NjU4OTEsIm5iZiI6MTcyODQ2NTU5MSwicGF0aCI6Ii8xMzU3MDM2MDMvMzc0ODYyOTQxLTM3OGMzMTI1LTgwZTktNGNlYi05MjMwLWIxZTY1ZjQ1YWVhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOVQwOTE5NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZWQ3OWFlYWRjYWVhYWY4YzhkMjE3YjY1ZDQyNmY4MmU5MmE5NDViYjViNjg4YWM0YzI3YzgxMzVjZWQ0NThhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vMMtdQy7uPmNDveqXDqbRnPJG_bLbA0mYOuWmysVlEU)

_Originally posted by @aksueikava in https://github.com/N3M1X10/zapret_build/issues/3#issuecomment-2401610522_

**Comment by Dre2dn0ught** [comment]
Служба корректно создаётся только с родной папки на рабочем столе, с других мест не работает.

**Comment by N3M1X10** [comment]
У меня есть предположение что Контроль учётных записей (UAC) может быть виной

**Comment by N3M1X10** [comment]
### Способ через отключение UAC

1) `win+x` сочетание клавиш
2) запустить командную строку **от имени администратора** (или PowerShell)

3) чтобы выключить UAC:

`REG ADD HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System /v EnableLUA /t REG_DWORD /d 0 /f`

**После внесения изменения Перезагрузить ПК !**

4) Чтобы вернуть UAC назад:
`REG ADD HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System /v EnableLUA /t REG_DWORD /d 1 /f`
Также перезагрузиться для применения 

---

После попробуйте создать службу

**Comment by Dre2dn0ught** [comment]
Нет, отключение UAC не помогло.

**Comment by Dre2dn0ught** [comment]
Ещё потестил, служба стартует с корня любого диска, но не стартует если её перенести в любую условную папку(для сортировки)

**Comment by burnedoutman** [comment]
потому что бэкслеши скорее всего нужно поправить, как я тут сделал https://github.com/Flowseal/zapret-discord-youtube

**Comment by burnedoutman** [comment]
@N3M1X10 верни пожалуйста в сборку папку tools
тем у кого не заработает универсальное решение, поможет blockcheck, чтобы подобрать подходящие параметры

**Comment by N3M1X10** [comment]
> @N3M1X10 верни пожалуйста в сборку папку blockcheck тем у кого не заработает универсальное решение, поможет blockcheck, чтобы подобрать подходящие параметры

Готово
